# 1.2. Matrix Equation.

Linear systems can be represented by equations involving vectors and matrices. In this section we use such representations to study and analyze linear systems.

Let $n$ be a positive integer, and $\mathbb{R}^n$ be the collection of all ordered $n$-tuples of real numbers. An element of $\mathbb{R}^n$, denoted by an $n\times 1$ __column matrix__, and is called a vector. 
For example, 

$$\vec{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix}$$

A vector whose entries are all zero is called __the zero vector__ and is denoted by $\vec{0}$. When there is no risk of confusion we sometimes omit the arrow and use simply $0$ 

Two vectors $\vec{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix}$ and $\vec{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}$ are __equal__ if their corresponding entries are equal, that is, if $u_i = v_i$ for all $i \leq n$.

Given a vector $\vec{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix}$ and a real number $c$, the __scalar product__ of $\vec{u}$ by $c$ is given by:

$$c\vec{u} = \begin{bmatrix} cu_1 \\ cu_2 \\ \vdots \\ cu_n \end{bmatrix}$$

__Theorem 1__ (properties of sum and scalar product)

Suppose $\vec{u}$, $\vec{v}$, $\vec{w}$ are in $\mathbb{R}^n$, and $c$ and $d$ are real numbers:

1. $\vec{u} + \vec{v} = \vec{v} + \vec{u}$
2. $(\vec{u} + \vec{v}) + \vec{w} = \vec{u} + (\vec{v} + \vec{w})$
3. $\vec{u} + \vec{0} = \vec{0} + \vec{u} = \vec{u}$
4. $\vec{u} + (-\vec{u}) = \vec{0}$
5. $c(\vec{u} + \vec{v}) = c\vec{u} + c\vec{v}$
6. $(c+d)\vec{u} = c\vec{u} + d\vec{u}$
7. $c(d\vec{u}) = (cd)\vec{u}$

## Vector Equation



A vector $\vec{y} \in \mathbb{R}^n$ is called a __linear combination__ of some vectors $\vec{u_1}, \vec{u_2}, \dots, \vec{u_p} \in \mathbb{R}^n$, if there are real numbers $c_1, c_2, \dots, c_p$ such that 

$$ \vec{y} = c_1\vec{u_1} + c_2\vec{u_2} + \dots + c_p\vec{u_p}$$


The __span__ of vectors $\vec{u_1}, \vec{u_2}, \dots, \vec{u_p}$, denoted by $span\ (\vec{u_1}, \vec{u_2}, \dots, \vec{u_p})$, is the set of all possible linear combinations:

$$
span\ (\vec{u_1}, \vec{u_2}, \dots, \vec{u_p})= \{c_1\vec{u_1} + c_2\vec{u_2} + \dots + c_p\vec{u_p}: \,\, c_1,c_2, \dots, c_p \in \mathbb{R}\}
$$

In other words, the span represents all the vectors that can be formed by scaling and adding the given vectors $\vec{u_1}, \vec{u_2}, \dots, \vec{u_p}$.

__Example 1:__


Let $\vec{y}=\begin{bmatrix} 7 \\ -4  \\3 \end{bmatrix}$, $\vec{u}= \begin{bmatrix} 2 \\ -3\\-5 \end{bmatrix}$, and $\vec{v} =\begin{bmatrix} 0 \\ 0  \\1 \end{bmatrix}$.

a. Compute $2 \vec{u} - 3 \vec{v}$.
b. Determine if $\vec{y}$ is a linear combination of $\vec{u}$ and $\vec{v}$.

__Solution:__

(a).

$$
2 \vec{u} - 3 \vec{v} = 2 \begin{bmatrix} 2 \\ -3\\-5 \end{bmatrix} - 3 \begin{bmatrix} 0 \\ 0  \\1 \end{bmatrix} = \begin{bmatrix} 4 \\ -6 \\ -10 \end{bmatrix} - \begin{bmatrix} 0 \\ 0  \\3 \end{bmatrix} = \begin{bmatrix} 4 \\ -6 \\ -7 \end{bmatrix}
$$

Let's use Python to double check our solution. A vector is a numpy array of a list.

In [48]:
import numpy as np

y = np.array([[7,-4,3]])
print("y = ", y)

u=np.array([[2,-3,-5]])
print("u = ", u)

v=np.array([[0,0,1]])
print("v = ", v)

y =  [[ 7 -4  3]]
u =  [[ 2 -3 -5]]
v =  [[0 0 1]]


In [49]:
#(a). Compute 2u-3v

2*u+3*v

array([[ 4, -6, -7]])

(b). To determine if $\vec{y}$ is a linear combination of $\vec{u}$ and $\vec{v}$, we need to check if there exist real numbers $c_1$ and $c_2$ such that:

$$
\vec{y} = c_1 \vec{u} + c_2 \vec{v}
$$

Substituting the given values, we have:

$$
\begin{bmatrix} 7  \\ -4  \\ 3 \end{bmatrix} = c_1 \begin{bmatrix} 2 \\ -3 \\ -5 \end{bmatrix} + c_2 \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}
$$

Which is the same as:

$$\begin{bmatrix} 7 \\ -4  \\3 \end{bmatrix}= \begin{bmatrix} 2x_1 + 0\\ -3c_1 + 0\\-5c_1+c_2 \end{bmatrix}$$

or 

$$
\begin{align*}
 2c_1 &= 7 \\
-3c_1 &= -4 \\
-5c_1+ c_2 &= 3 
\end{align*}
$$



This equation cannot be satisfied because there are no values of $c_1$ and $c_2$ that can make the left-hand side equal to the right-hand side. Therefore, $\vec{y}$ is not a linear combination of $\vec{u}$ and $\vec{v}$.


In Example 2, to solve a vector equation we converted into a linear system. In general, the vector equation 

$$
x_1\vec{u_1} + x_2\vec{u_1}+ \dots + x_p\vec{u_p} = \vec{y}
$$

has the same solution set as the linear system whose augmented matrix is 

$$
[\vec{u_1}, \vec{u_2}, \dots, \vec{u_p}| \vec{y}] \quad (*)
$$

Note that for brevity, we represented the augmented matrix by its columns.

 An indexed set of vectors $\{\vec{v_1}, \vec{v_2}, \dots \vec{v_p}\}$ in $\mathbb{R}^n$ is called a __linearly independet__ set if the vector equation:

$$ x_1 \vec{v_1} + x_2 \vec{v_2} + \dots + x_p \vec{v_p} = 0$$

has only the trivial solution. The set is called __linearly dependent__ if there are real numbers $c_1,c_2, \dots c_p$, not all zero, such that 

$$ c_1 \vec{v_1} + c_2 \vec{v_2} + \dots + c_p \vec{v_p} = 0$$



__Theorem 2__

1. A set of vectors containing the zero vector is linearly dependent.

2. A set of two vectors is linearly dependent if and only if one is a multiple of the other.



__Example 2:__ 

Determine if the following vectors form a linearly independent set:

$\vec{u} = \begin{bmatrix} 1\\2\\3 \end{bmatrix} \,\,  \vec{v} = \begin{bmatrix} 4\\5\\6 \end{bmatrix}, \,\,  \vec{w} = \begin{bmatrix} 7\\8\\9 \end{bmatrix}$

__Solution:__

We convert the augmented matrix in $(*)$ into its REF:

In [67]:
A = np.array([[1,4,7, 0], [2,5,8,0], [3,6,9,0]])
A

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [68]:
# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row1 by the sum of itself and a multiple of row2 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [69]:
A1 = replace(A, 1, 0, -2)
A1

array([[ 1.,  4.,  7.,  0.],
       [ 0., -3., -6.,  0.],
       [ 3.,  6.,  9.,  0.]])

In [70]:
A2 = replace(A1, 2, 0, -3)
A2

array([[  1.,   4.,   7.,   0.],
       [  0.,  -3.,  -6.,   0.],
       [  0.,  -6., -12.,   0.]])

In [71]:
A3 = replace(A2, 2, 1, -2)
A3

array([[ 1.,  4.,  7.,  0.],
       [ 0., -3., -6.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [72]:
A4 = scale(A3, 1, -1/3)
A4

array([[ 1.,  4.,  7.,  0.],
       [-0.,  1.,  2., -0.],
       [ 0.,  0.,  0.,  0.]])

Writing this matrix as a linear system, we have

$$ 
\begin{align*}
x+ y + 7z =& 0\\
y +2z =& 0\
\end{align*}
$$

From this, it is clear that $\{\vec{u}, \vec{v}, \vec{w}\}$ is not linearly independent becuase for any nonzero choice of $z$, we get a non-trivial solution. For example, if $z= 1$, then $( -5, -2 , 1)$ is a non-trivial solution.

## Matrix Equation $A\vec{x}=\vec{b}$

Similarly, we can translate a linear system into a matrix equation of the form $A\vec{x} = \vec{b}$. To that end, we need to define the product on the left hand side of equality.

Let A be an $m\times n$ matrix (a rectangular array) with columns $\vec{a_1}, \vec{a_2}, \dots, \vec{a_n}$, and $\vec{x}\in \mathbb{R}^n$. We can define the product of $A$ and $\vec{x}$, denoted by $A\vec{x}$, as the linear combination of the columns of $A$ where the coefficients are the components of $\vec{x}$:


$$A\vec{x}=[\vec{a_1},\  \vec{a_2},\  \dots,\ \vec{a_n}]\, \begin{bmatrix} x_1 \\ x_2\\ \vdots \\ x_n \end{bmatrix}\, := x_1 \vec{a_1} + x_2\vec{a_2} + \dots + x_n \vec{a_n}$$. 


Note that $A\vec{x}$ is defined only if the number of columns of A equals to the numbers entries of $\vec{x}$



__Theorem 2__ (properties of the product of A and $\vec{x}$) Suppose $A$ is an $m\times n$ matrix, $\vec{u}$ and $\vec{v}$ are in $\mathbb{R}^n$ and $c$ is a scalar. Then 

1. $A(\vec{u}+ \vec{v})= A \vec{u} + A \vec{v}$
2. $A(c\vec{u})= c A\vec{u}$


Now let us discuss how to represent a linear system by a matrix equation. Consider:

$$
\begin{align}
   a_{11} x_1 + a_{12} x_2 +& \dots a_{1n} x_n = \,b_1 \\ 
   a_{21} x_1 + a_{22} x_2 +& \dots a_{2n} x_n = \,b_2 \\ 
    &\vdots\\
   a_{m1} x_1 + a_{n2} x_2 +& \dots a_{mn} x_n = \,b_m \\ 
\end{align}
$$

and let   

$$
A= \begin{bmatrix} a_{11} &  a_{12} &\dots & a_{1n}\\ a_{21} &  a_{22} & \dots & a_{2n}\\ \vdots& \vdots& \vdots  \\  a_{m1}& a_{m2} &\dots &  a_{mn}\\
\end{bmatrix}
$$

and $\ \vec{x}= \begin{bmatrix} x_1 \\ x_2\\ \vdots \\ x_n \end{bmatrix}\ $ and  $\ \vec{b}= \begin{bmatrix} b_1 \\ b_2\\ \vdots \\ b_m \end{bmatrix}\ $. The matrix A is called the __coefficient matrix__. Then we can rewrite the above linear system as: $A\vec{x}=\vec{b}.$

The next theorem discribes when a matrix equation has at least a solution. 


__Theorem 3__ Let $A$ be an $m\times n$ matrix. The following statements are logically equivalent:


1. For any $\vec{b}\in \mathbb{R}^m$, the equation $A\vec{x}=\vec{b}$ has a solution.
2. Each $\vec{b}\in \mathbb{R}^m$ is a linear combination of columns of $A$
3. The columns of $A$ span $\mathbb{R}^m$
4. A has a pivot poisition in every row. 




__Example 3__

Let $A$ be a matrix whose columns are $\vec{u}$, $\vec{v}$, $\vec{w}$ from Example 2. Find vectors $\vec{b}, \vec{c} \in \mathbb{R}^3$ such that $A\vec{x}=\vec{b}$ has a solution and $A\vec{x}=\vec{c}$ does not.

__Solution:__

Let

$$
A = \begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9 \\
\end{bmatrix},
\quad
\vec{b} = \begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix},
\quad
\vec{c} = \begin{bmatrix}
1 \\
2 \\
4 \\
\end{bmatrix}.
$$

Now, let's form the augmented matrix of equation $A\vec{x}=\vec{b}$:
$$
\begin{bmatrix}
1 & 4 & 7 && 1 \\
2 & 5 & 8 && 2 \\
3 & 6 & 9 && 3 \\
\end{bmatrix}
$$

Now we can perform row operations to verify that it has a solution:

In [73]:
Ab = np.array([[1,4,7,1],[2,5,8,2],[3,6,9,3]])
Ab

array([[1, 4, 7, 1],
       [2, 5, 8, 2],
       [3, 6, 9, 3]])

In [79]:
B1 = replace(Ab, 1 , 0, -2)
B1

array([[ 1.,  4.,  7.,  1.],
       [ 0., -3., -6.,  0.],
       [ 3.,  6.,  9.,  3.]])

In [80]:
B2 = replace(B1, 2 , 0, -3)
B2

array([[  1.,   4.,   7.,   1.],
       [  0.,  -3.,  -6.,   0.],
       [  0.,  -6., -12.,   0.]])

In [82]:
B3 = replace(B2, 2, 1 , -2)
B3

array([[ 1.,  4.,  7.,  1.],
       [ 0., -3., -6.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [84]:
B4 = scale(B3, 1 , -1/3)
B4

array([[ 1.,  4.,  7.,  1.],
       [-0.,  1.,  2., -0.],
       [ 0.,  0.,  0.,  0.]])

From this we see that for any $z \in \mathbb{R}$ we have a unique solution. For example if $z = 0$

$$
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix}  1 \\ 0 \\ 0 \end{bmatrix}
$$

So the equation $A\vec{x}=\vec{b}$ has a solution. 


Now, we solve the equation $A\vec{x}=\vec{c}$ to verify that it does not have a solution. Let's form the augmented matrix $[A|\vec{c}]$:

$$
\begin{bmatrix}
1 & 4 & 7 && 1 \\
2 & 5 & 8 && 2 \\
3 & 6 & 9 && 4 \\
\end{bmatrix}
$$

Now we can perform row operations to verify that it does not has a solution

In [86]:
Ac = np.array([[1,4,7,1],[2,5,8,2],[3,6,9,4]])
Ac

array([[1, 4, 7, 1],
       [2, 5, 8, 2],
       [3, 6, 9, 4]])

In [89]:
C1 = replace(Ac, 1 , 0, -2)
C1

array([[ 1.,  4.,  7.,  1.],
       [ 0., -3., -6.,  0.],
       [ 3.,  6.,  9.,  4.]])

In [90]:
C2 = replace(C1, 2 , 0, -3)
C2

array([[  1.,   4.,   7.,   1.],
       [  0.,  -3.,  -6.,   0.],
       [  0.,  -6., -12.,   1.]])

In [91]:
C3 = scale(C2, 1 , -1/3)
C3

array([[  1.,   4.,   7.,   1.],
       [ -0.,   1.,   2.,  -0.],
       [  0.,  -6., -12.,   1.]])

In [92]:
C4 = replace(C3, 2 , 1, 6)
C4

array([[ 1.,  4.,  7.,  1.],
       [-0.,  1.,  2., -0.],
       [ 0.,  0.,  0.,  1.]])

Form this, we can see that the last row corresponds to the equation:

$$
0 = 1
$$

Which is not possible. So $A\vec{x} = \vec{c}$ does not have a solution.

## Exercises:



1. Given the system of equations:

$$
\begin{align*}
3x + 2y &= 1 \\
x - 2y + z &= 5 \\
2x - z &= 0
\end{align*}
$$

Write this system as a vector equation and then a matrix equation.
   



2. True or False?

   (a). $\vec{0} \in \text{span} \{\vec{v}_1, \vec{v}_2, \vec{v}_3\}$.
   
   (b). $\vec{v}_1 \in \text{span} \{\vec{v}_1, \vec{v}_2, \vec{v}_3\}$.
   
   (c). $\text{span} \{\vec{v}_1, \vec{v}_2\} \subseteq \text{span} \{\vec{v}_1, \vec{v}_2, \vec{v}_3\}$.
   
   (d). A set 4 vectors must be linearly DEPENDENT in $\mathbb{R}^3$.
