# 1.3 Solution set of linear Systems.

In this section, we study and analyze the solution set of linear systems.

## Homogenous Linear Systems

We start with describing the solution set of a simpler linear systems where the right side of equalities are zeros. In matrix form, $A\vec{x}=\vec{0}$; such system is called __homogeneous__. Homogeneous systems are always consistent since $\vec{x}=\vec{0}$ is always a solution. We call $\vec{0}$ the trivial solution of $A\vec{x}=\vec{0}$. 

__Theorem 2:__

The homogenous system $A\vec{x}=\vec{0}$ has a nontrivial solution if and only if it has a non-pivot column. 

Non-pivot columns correspond to __free variables__; all other variables can be expressed in terms of free variables. 

__Example 1__

Describe the solution set of $10x -4y+ 7z=0$

__Solution__: consider the augmented matrix of the system: $ \begin{bmatrix} 10& -4& 7&& 0\\ \end{bmatrix}$. There is only one pivot columns and y and z are free variables.



$$
\vec{x} = \begin{bmatrix} x \\ y \\z \end{bmatrix} = \begin{bmatrix} 0.4y - 0.7z \\y\\z \end{bmatrix}= \begin{bmatrix} 0.4y \\ y \\0 \end{bmatrix} + \begin{bmatrix} - 0.7z \\ 0 \\ z \end{bmatrix}= 
y \begin{bmatrix} 0.4 \\ 1 \\ 0\end{bmatrix} + z \begin{bmatrix} 0.7 \\0\\1 \end{bmatrix}
$$

Thus, the solution set is span ( $\ \begin{bmatrix} 0.4 \\ 1 \\ 0\end{bmatrix},\, \begin{bmatrix} 0.7 \\0\\1 \end{bmatrix}\ $)


__Example 2__

Determine if the following system has a nontrivial solution. Then describe the solution set.

$$
\begin{align*}
3x +5y - 4z &= 0 \\
-3x -2y +4z &= 0 \\
6x + y -8 z &= 0
\end{align*}
$$
 
We first setup the augmented matrix, and then, we find its REF:

In [87]:
import numpy as np

A= np.array([[3,5,-4, 0], [-3, -2, 4, 0], [6, 1, -8, 0]])
A

array([[ 3,  5, -4,  0],
       [-3, -2,  4,  0],
       [ 6,  1, -8,  0]])

In [88]:
# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row1 by the sum of itself and a multiple of row2 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [89]:
A_1 = replace(A, 1,0, 1)
A_1

array([[ 3.,  5., -4.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 6.,  1., -8.,  0.]])

In [90]:
A_2 = replace(A_1, 2,0, -2)
A_2

array([[ 3.,  5., -4.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 0., -9.,  0.,  0.]])

In [91]:
A_3 = replace(A_2, 2, 1, 3)
A_3

array([[ 3.,  5., -4.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

We can see that the third column is a non-pivot column and therefore $z$ is a free variable. Thus, $A\vec{x}=0$ has (infinitely many) one for each choice of $z$. To find the solution set we write back the linear system coresponding to REF of A: 

$$
\begin{align*}
3x +5y - 4z &= 0 \\
3y &= 0 \\
 0&= 0
\end{align*}
$$

Therefore, $x= \frac{-4}{3}z$, and the slution set contains vectors of the foloowing form:


$$
\vec{x} = \begin{bmatrix} x\\y\\z \end{bmatrix} = \begin{bmatrix} \frac{-4}{3}z\\0\\z \end{bmatrix}= z \begin{bmatrix} \frac{-4}{3}\\0\\1 \end{bmatrix}
$$

for $z\in \mathbb{R}$.

In other words, the solution set is $\text{span}\ (\ \begin{bmatrix} \frac{-4}{3}\\0\\1 \end{bmatrix}\ )$





We can represnt a linear independence equation

$$ x_1 \vec{v_1} + x_2 \vec{v_2} + \dots + x_p \vec{v_p} = 0$$

by a homogenous system $A\vec{x} = 0$ where $A$ is a matrix whose columns are $\vec{v_i}s$. In fact, we have:

__Theorem 3__

The columns of a matrix $A$ form a linearly independent set if and only if $A\vec{x}=0$ has only trivial solution.

__Example 3__ 

Determine if the columns of the matrix $A = \begin{bmatrix} 2 & 3 & 5\\ -1 & 1 & 1\\ 5 & 4 & 5    \end{bmatrix}$ form a linearly independent set. 

__Solution:__

We show $A\vec{x}= 0$ has a nontrivial solution, and therefore, by Theorem 3, the columns of $A$ are linearly indendent. 

In [92]:
A = np.array([[2,3,5,0], [-1,1,1,0], [5, 4, 5,0]])
A

array([[ 2,  3,  5,  0],
       [-1,  1,  1,  0],
       [ 5,  4,  5,  0]])

In [93]:
A1 = swap(A, 1,0) 
A1

array([[-1.,  1.,  1.,  0.],
       [ 2.,  3.,  5.,  0.],
       [ 5.,  4.,  5.,  0.]])

In [94]:
A2 = scale(A1 , 0, -1)
A2

array([[ 1., -1., -1., -0.],
       [ 2.,  3.,  5.,  0.],
       [ 5.,  4.,  5.,  0.]])

In [95]:
A3 = replace(A2, 1,0,-2)
A3

array([[ 1., -1., -1., -0.],
       [ 0.,  5.,  7.,  0.],
       [ 5.,  4.,  5.,  0.]])

In [96]:
A4 = replace(A3, 2,0,-5)
A4

array([[ 1., -1., -1., -0.],
       [ 0.,  5.,  7.,  0.],
       [ 0.,  9., 10.,  0.]])

In [97]:
A5 = scale(A4, 1, 1/5)
A5

array([[ 1. , -1. , -1. , -0. ],
       [ 0. ,  1. ,  1.4,  0. ],
       [ 0. ,  9. , 10. ,  0. ]])

In [98]:
A6 = replace(A5, 2,1, -9)
A6

array([[ 1. , -1. , -1. , -0. ],
       [ 0. ,  1. ,  1.4,  0. ],
       [ 0. ,  0. , -2.6,  0. ]])

Representing this as a linear system, the last row of $A_6$ shows that $z = 0$, and thefore, $y = x= 0$. In other words, the only solution to this system is zero.

## General Case: the solution set of non-homogenoues linear system:

__Theorem 3__ 

Let $A\vec{x}=\vec{b}$ be a consistent system, and let $\vec{p}$ be a solution. Then the solution set of $A\vec{x}=\vec{b}$ is the set of all vectors of the form $\vec{p}+\vec{h}$ where $\vec{h}$ is any solution to the homogenoues system $A\vec{x}=0$.



__Example 4__ Describe the solution set of $A\vec{x}=\vec{b}$ where 


$A=\begin{bmatrix} 3& 5& -4\\ -3& -2& 4\\ 6& 1& -8 \end{bmatrix}$ and $\vec{b}= \begin{bmatrix} 7\\ -1\\ -4\\  \end{bmatrix}$.

__Solution__ :

In [99]:
# set up the augemented matrix [A|b]
A = np.array([[3,5,-4,7], [-3,-2, 4,-1], [6,1,-8,-4]])
A

array([[ 3,  5, -4,  7],
       [-3, -2,  4, -1],
       [ 6,  1, -8, -4]])

In [100]:
# Row reduce the augmented matrix to reduced echelon form:

A1 = replace(A, 1,0,1)
A1

array([[ 3.,  5., -4.,  7.],
       [ 0.,  3.,  0.,  6.],
       [ 6.,  1., -8., -4.]])

In [101]:
A2 = replace(A1, 2, 0, -2)
A2

array([[  3.,   5.,  -4.,   7.],
       [  0.,   3.,   0.,   6.],
       [  0.,  -9.,   0., -18.]])

In [102]:
A3 = replace(A2, 2, 1, 3)
A3

array([[ 3.,  5., -4.,  7.],
       [ 0.,  3.,  0.,  6.],
       [ 0.,  0.,  0.,  0.]])

In [103]:
A4 = replace(A3, 0, 1, -5/3)
A4

array([[ 3.,  0., -4., -3.],
       [ 0.,  3.,  0.,  6.],
       [ 0.,  0.,  0.,  0.]])

In [104]:
A5 = scale(A4, 0, 1/3)
A5

array([[ 1.        ,  0.        , -1.33333333, -1.        ],
       [ 0.        ,  3.        ,  0.        ,  6.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [105]:
A6 = scale(A5, 1, 1/3)
A6

array([[ 1.        ,  0.        , -1.33333333, -1.        ],
       [ 0.        ,  1.        ,  0.        ,  2.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

Now we can express each dependent variable in terms of free variables:

We have $x_1 - \frac{4}{3} x_3 = -1$, $x_2= 2$, and $x_3$ is free. As a vector, the general solution of $A\vec{x}=\vec{b}$ is 

$$\begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ \end{bmatrix} = \begin{bmatrix} -1 + \frac{4}{3} x_3\\ 2\\ x_3\end{bmatrix} = \begin{bmatrix} -1 \\ 2 \\ 0 \end{bmatrix} + x_3 \begin{bmatrix} \frac{4}{3} \\ 0 \\ 1 \end{bmatrix}$$

## Exercises

1.  Is $\left\lbrace\ \  \begin{bmatrix} 1 \\ 2  \\3 \end{bmatrix},  
\begin{bmatrix} 4 \\ 5  \\6 \end{bmatrix}, \begin{bmatrix} 7 \\ 8 \\9 \end{bmatrix}\ \ \right\rbrace$ linearly independent or dependent?

2. Describe the solution set of $A\vec{x}=\vec{b}$ where 

$$
A = \begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9 \\
\end{bmatrix},
\quad
\vec{b} = \begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix},
$$