# 2. Matrix Algebra

This section focuses on matrix algebra and its properties. We will also explore how operations involving matrices are connected to linear systems.

## Matrices

Consider matrix $A$, which is an $m \times n$ matrix with $m$ rows and $n$ columns:

$$
A = \begin{bmatrix} a_{11} &  a_{12} &\dots & a_{1n}\\ a_{21} &  a_{22} & \dots & a_{2n}\\ \vdots& \vdots& \vdots  \\  a_{m1}& a_{m2} &\dots &  a_{mn}\\
\end{bmatrix}
$$

The entry in the $i$th row and $j$th column is referred to as the __$(i,j)$-entry__ of matrix $A$. Entries with the same row and column index ($a_{i,i}$ for any $i$) are called __diagonal entries__ of $A$. The $i$th column of $A$, denoted as $a_i$, represents a vector in $\mathbb{R}^m$. We can represent matrix $A$ in a compact form by its columns:

$$
A= \begin{bmatrix} a_{1} &  a_{2} &\dots & a_{n}\\ \end{bmatrix},
$$

or by its entries:

$$A= (a_{i,j})$$

A matrix whose entries are all zero is called a __zero matrix__, denoted by $0$. The size of a zero matrix is usually clear from the context. 

An $n \times n$ matrix is called: 

1. the __identity matrix__, denoted by $I_n$, if it has 1 on the diagonal and 0 everywhere else. 
2.  a __diagonal matrix__ if it has all nondiagonal entries equal to zero. Identity matrices are diagonal.
3. an __upper triangular matrix__ if it has all entries below the diagonal equal to zero.
4. a _lower triangular matrix_ if it has all entries above the diagonal equal to zero.
5.  a_triangular matrix_ if it is either upper triangular or lower triangular.

__Example 1__

Let $A = \begin{bmatrix} 0 & 2 & -1\\ 2 & 3 & 1 \end{bmatrix}$. 

As we have seen before, we use NumPy arrays to represent A. Note that each list in the array represent a row of A.

In [1]:
import numpy as np

A = np.array([[0, 2, -1],[2, 3, 1]])
print('A =\n', A)


A =
 [[ 0  2 -1]
 [ 2  3  1]]


$A$ is a $2 \times 3$ matrix. The following cell shows how to find the size of $A$:

In [2]:
#Size of A

print('A has ', A.shape[0],  'rows, and', A.shape[1],  'columns')

A has  2 rows, and 3 columns


We can also print rows and columns of $A$:

In [3]:
print('The first row of A is ', A[0,:])

print(30*'*')

print('\n The second row of A is ', A[1,:])

print(30*'*')

print('\n The first column of A is ', A[:,0])

print(30*'*')

print('\n The second column of A is ', A[:,1])

print(30*'*')

print('\n The third column of A is ', A[:,2])



The first row of A is  [ 0  2 -1]
******************************

 The second row of A is  [2 3 1]
******************************

 The first column of A is  [0 2]
******************************

 The second column of A is  [2 3]
******************************

 The third column of A is  [-1  1]


The following cell shows how to generate an identity matrix of an arbitary size:

In [4]:
# 3x3 identity matrix
I_3 = np.eye(3)

print('I_3 = \n \n', I_3)

# 4x4 identity matrix I_4
I_4 = np.eye(4)

print('\n I_4 = \n \n', I_4)

# 5x5 identity matrix I_5
I_5 = np.eye(5)

print('\n I_5 = \n \n', I_5)

I_3 = 
 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 I_4 = 
 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 I_5 = 
 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Let's have more examples:

In [5]:
B = np.array([[1, 2, 3],[4, 5, 6]])
print('B =\n', B)


#Size of B

print('\n B has ', B.shape[0],  'rows, and', B.shape[1],  'columns')

# the second column of B

print('\n The second column of B is ', B[:,1])

print(30*'*')

C = np.array([[0, 2] ,[2, 3],[5, -2]])
print('\n C = \n', C)


#Size of C

print('\n C has ', C.shape[0],  'rows, and', C.shape[1],  'columns')


# print the columns of C

for i in range(C.shape[1]):
    print('\n The', i+1, '-th column of C is ', B[:,i])



B =
 [[1 2 3]
 [4 5 6]]

 B has  2 rows, and 3 columns

 The second column of B is  [2 5]
******************************

 C = 
 [[ 0  2]
 [ 2  3]
 [ 5 -2]]

 C has  3 rows, and 2 columns

 The 1 -th column of C is  [1 4]

 The 2 -th column of C is  [2 5]


## Basic Algebraic Operations

The arithmetic operations defined for vectors can be extended to matrices:

1. Two matrices $A$ and $B$ are equal if they have the same size and entries.



2. The __sum__ of matrices is defined for matrices of the same size: 

let $A = (a_{ij})$ and $B = (b_{ij})$ be two $m \times n$ matrices. Then $A+B$ is an $m \times n$ matrix whose entries are the sums of the corresponding entries of $A$ and $B$:

$$ A+B = (a_{ij} + b_{ij}).$$



3. The __scalar product__ $cA$ for a scalar $c \in \mathbb{R}$ and a matrix $A$ is a matrix of the same size as $A$ whose entries are $c$ times the entries of $A$:

$$ cA = (ca_{ij}) $$

__Theorem 1__ (properties of sum and scalar product)

Let $A$, $B$, and $C$ have the same size, and let $c$ and $d$ be real numbers.

1. $A+B = B+A$
2. $(A+B)+C = A+(B+C)$
3. $A+ 0 = A$
4. $c(A+B) =  cA + cB$
5. $(c+d)A = cA + dA$
6. $c(dA)=(cd)A$

__Example 2:__ 

Consider the matrices in Example 1. Compute the following:

1. $3A-B$

2. $A+C$

__Solution:__

In [6]:
#1

3*A-B

array([[-1,  4, -6],
       [ 2,  4, -3]])

$A+C$ is not defined because $A$ and $C$ are not of the same size:

In [7]:
#2.
A + C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## Matrix Product


Let $A$ be an $m \times n$ and $B$ be an $n \times p$ matrix. The product AB is an $m\times p$ matrix whose columns are $Ab_1, Ab_2, \dots, Ab_p$:

$$
AB= \begin{bmatrix} Ab_{1} &  Ab_{2} &\dots & Ab_{n}\\ \end{bmatrix}.
$$

We can also descibe the matrix product by the entries: the ($ij$)-entry of $AB$ is the product of the $i$th-row of $A$ and the $j$th column of $B$ in the following way:

$$
a_ib_j = \begin{bmatrix} a_{i1} &  a_{i2} &\dots & a_{in}\\ \end{bmatrix} \begin{bmatrix} b_{1j} &  b_{2j} &\dots & a_{nj}\\ \end{bmatrix} = a_{i1}b_{j1} + a_{i2}b_{2j} + \dots + a_{in}b_{nj} = \Sigma^{n}_{k=1}a_{ik}b_{kj}
$$


The product $BA$ is not defined if $p\neq m$ (the _neighboring dimensions_
do not match).


__Example 3__

Let $A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$ and $B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\\ \end{bmatrix}$. Compute $AB$ and $BA$.

__Solution:__ 

$A$ is a $2 \times 3$ and B is a $3 \times 2$ matrix; so the product is defined. In Python we use the sympol `@` to compute the matrix product

In [8]:
import numpy as np

#A
A = np.array([[1,2,3],[4,5,6]])

#B
B = np.array([[1,2],[3,4],[5,6]])

#Compute the matrix product
AB = A @ B

print(AB)

[[22 28]
 [49 64]]


Now let's compute $BA$:

In [9]:
#Compute the product BA
BA = B @ A

print(BA)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


__Example 4__ 

Let $C = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 4 & 5 & 6 & 7 \end{bmatrix}$. The matrix product $AC$ is not defined because the number of columns in matrix $A$ does not match the number of rows in matrix $C$. If we proceed with computing $AC$ we will get: 

In [10]:
C = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

# Compute AC
AC = A @ C

print(AC)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

__Power of Square Matrices__

We can raise a square matrix $A$ to the power of a natural number using matrix multiplication. The matrix power is a fundamental idea in several linear algebra applications such as the long-term behavior of disceret dynamical systems. 

__Example 5:__

Let $M = BA$ where $A$ and $B$ are matrices in Example 3. Compute $M^{4}$.

In [11]:
#C
M = BA
#Compute C^4
M4 = M @ M @ M @ M

print('C^4 =\n ', M4 )

C^4 =
  [[ 5447976  7470048  9492120]
 [11879096 16288144 20697192]
 [18310216 25106240 31902264]]


Interestingly, computing the power of diagonal matrices is relatively straightforward.

__Example 6:__

Let's consider the matrix $A = \begin{bmatrix} 2 & 0\\ 0 & 5 \end{bmatrix}$. We can observe the pattern for computing powers of $A$:

- $A^2 = \begin{bmatrix} 2^2 & 0\\ 0 & 5^2 \end{bmatrix} = \begin{bmatrix} 4 & 0\\ 0 & 25 \end{bmatrix}$

- $A^3 = \begin{bmatrix} 2^3 & 0\\ 0 & 5^3 \end{bmatrix} = \begin{bmatrix} 8 & 0\\ 0 & 125 \end{bmatrix}$

- $A^4 = \begin{bmatrix} 2^4 & 0\\ 0 & 5^4 \end{bmatrix} = \begin{bmatrix} 16 & 0\\ 0 & 625 \end{bmatrix}$

We can observe that $A^k$ is a diagonal matrix of the same size with the diagonal elements being obtained by raising the corresponding diagonal elements of $A$ to the power of $k$.

In [12]:
import numpy as np

A = np.array([[2,0],[0,5]])

A2 = A @ A
A2

array([[ 4,  0],
       [ 0, 25]])

In [13]:
A3 = A2 @ A
A3

array([[  8,   0],
       [  0, 125]])

In [14]:
A4 = A3 @ A
A4

array([[ 16,   0],
       [  0, 625]])

__Theorem 2 (Properties of matrix product):__

Let $A$ be an $m\times n$ matrix, and let $B$ and $C$ be matrices of the same size for which the following sum and product operations are defined:

1. $A(BC) = (AB)C$


2. $A(B+C) = AB + AC$


3. $(B+C)A = BA + CA$


4. $r(AB) = (rA)B = A(rB)$ for any scalar $r\in \mathbb{R}$.


5. $I_mA = AI_n = A$

Recall that $I_n$ is the $n \times n$ identity matrix.


### Numerical Note

Numpy provides two other methods (built-in functions) to compute the matrix product: `numpy.dot` and `numpy.matmul`. 

They are both used to compute the product of two arrays (e.g., vectors, matrices, and even higher dimensional).

(1). If $A$ and $B$ are vectors (1-D arrays), they both perform dot product of vectors (which we will define in section 6) 

(2).  If $A$ and $B$ are non-vector matrices (2-D arrays), they both perform matrix multiplication, but using `numpy.matmul(A,B)` or `A @ B` is preferred.

(3) For scalar $r\in \mathbb{R}$ `numpy.dot(r,B)` is scalar product `r*B`. But `numpy.malmal(r,B)` and `r @ B` are not defined


__Example 6__

Let A, B, and C be the matrices defined in Example 3. Let's explore the differences between the above operations:

In [15]:
import numpy as np

#A
A = np.array([[1,2,3],[4,5,6]])

#B
B = np.array([[1,2],[3,4],[5,6]])


# for matrices (2D-arrays) of compatible size all methods return matrix product

print('\n A@B = \n', A@B)

print(10*'*')

print('\n np.dot(A,B) = \n', np.dot(A,B))

print(10*'*')

print('\n np.matmul(A,B) = \n', np.matmul(A,B))


 A@B = 
 [[22 28]
 [49 64]]
**********

 np.dot(A,B) = 
 [[22 28]
 [49 64]]
**********

 np.matmul(A,B) = 
 [[22 28]
 [49 64]]


In [16]:
# for vectors (1D arrays) dot and matmul return the dot product
C = [1,2,3]
D = [4,5,6]

print('\n np.dot(C,D) = \n', np.dot(C,D))

print(10*'*')

print('\n np.matmul(C,D) = \n', np.matmul(C,D))


 np.dot(C,D) = 
 32
**********

 np.matmul(C,D) = 
 32


In [17]:
# C@D is not defined for vectors

print('\n A@B = \n', C @ D)

TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [18]:
# If one argument is a real number, dot returns the scalar product
print('\n np.matmul(2,B) = \n', np.dot(A,2)) 


 np.matmul(2,B) = 
 [[ 2  4  6]
 [ 8 10 12]]


In [19]:
# If one argument is a real number  @ and matmul are not defined 
2 @ B

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [20]:
np.matmul (2,B)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

__Exercises:__

1. Which pair of the following matrices can be multiplied? Compute their matrix product.

$A = \begin{bmatrix}
1 & 3 \\
4 & -2 \\
3 & 2
\end{bmatrix}$

$B = \begin{bmatrix}
1 & 4 & 5\\
0 & 2  & 3
\end{bmatrix}$ 


$C = \begin{bmatrix}
1 & 3 & 0\\
2 & -1  & 3 \\
0 & 1 & 1
\end{bmatrix}$ 


2. Find two matrices $A$ and $B$ such that the products $AB$ and $BA$ are defined but $AB \neq BA$.


3.  Given $A= \begin{bmatrix}
1 & 2 \\ 1& 2 \end{bmatrix}$, find a nonzero matrix  $C$ for which $AC= \begin{bmatrix}
0 & 0 \\ 0 & 0
\end{bmatrix}$.
