# 2.4 Answers to Exercises

## 2.1 Matrix Algebra

1. Which pair of the following matrices can be multiplied? Compute their matrix product.

$A = \begin{bmatrix}
1 & 3 \\
4 & -2 \\
3 & 2
\end{bmatrix}$

$B = \begin{bmatrix}
1 & 4 & 5\\
0 & 2  & 3
\end{bmatrix}$ 


$C = \begin{bmatrix}
1 & 3 & 0\\
2 & -1  & 3 \\
0 & 1 & 1
\end{bmatrix}$ 

__Solution:__

In [1]:
import numpy as np

A = np.array([[1,3], [4,-2], [3,2]])

B = np.array([[1,4,5], [0,2,3]])

C = np.array([[1,3,0], [2,-1, 3], [0,1,1]])

None of $AA$, $BA$, $BB$, and $AC$ can be performed because the neighboring dimensions in none of the match. For example if we try to compute $AA$ in Python we get the following error:

In [8]:
A@A 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

On the other hand $AB$, $BC$, $CA$, $CB$, $CC$ can be performed:

In [6]:
A@B

array([[ 1, 10, 14],
       [ 4, 12, 14],
       [ 3, 16, 21]])

In [7]:
B@C

array([[ 9,  4, 17],
       [ 4,  1,  9]])

In [8]:
C@A

array([[ 7,  0,  9],
       [ 0, 10,  0],
       [ 2,  0,  4]])

In [7]:
C@C

array([[ 7,  0,  9],
       [ 0, 10,  0],
       [ 2,  0,  4]])

2. Find two matrices $A$ and $B$ such that the products $AB$ and $BA$ are defined but $AB \neq BA$.

__Solution:__

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

AB = A@B
BA = B@A

print('AB = \n', AB)

print('\nBA = \n', BA)

AB = 
 [[ 58  64]
 [139 154]]

BA = 
 [[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


3.  Given $A= \begin{bmatrix}
1 & 2 \\ 1& 2 \end{bmatrix}$, find a nonzero matrix  $C$ for which $AC= \begin{bmatrix}
0 & 0 \\ 0 & 0
\end{bmatrix}$.

__Solution__

There are infinitely many matrices such that $AC = 0$. We can set $C = \begin{bmatrix}
c_1 & C_2 \\ C_3 & C_4 \end{bmatrix}$ and solve $AC=0$ for C. For example one solution is $C = \begin{bmatrix}
-2 & 1 \\ 1 & 0.5 \end{bmatrix}$

In [10]:
A = np.array([[1,2], [1,2]])

C = np.array([[-2,1], [1, -0.5]]) 


A@C

array([[0., 0.],
       [0., 0.]])

## 2.2 Transpose, Inverse and Trace of matrices

1. Suppose $A= \begin{bmatrix}
1 & 2 \\
0 & -1 \\
3 & 0
\end{bmatrix}$

    (a) Compute $A^T$.
    
    (b) Is $AA^T$ invertible? 
    
    (c) Is $A^TA$ invertible?
    

__Solution:__

In [11]:
# part(a)

A = np.array([[1,2], [0,-1], [3,0]])

# compute transpose of A
A_T = np.transpose(A)

A_T

array([[ 1,  0,  3],
       [ 2, -1,  0]])

(b) 

__Solution 1__ Obviously a $3\times 2$ matrix has at most two linearly independent columns. It can be shown that $AA^T$ has the same amount of linearly independent columns. Thus $AA^T$ as a $3\times 3$ matrix, does not have three linearly independent columns and therefore, is not invirtible by invirtible matrix theorem.

__Solution 2__ Lets check and see if $AA^T$ row equivalent to identity matrix $I_3$

In [12]:
# part(b)

B = A @ A_T
B

array([[ 5, -2,  3],
       [-2,  1,  0],
       [ 3,  0,  9]])

 We form the augmented matrix $[AA^T\ |\ I_3]$ and use row operations to check if it is invertible: 

In [13]:
# 3x3 Identity matrix 
I3 = np.eye(3)

# Augmented matrix [AA^T, I_3]
M = np.concatenate((B, I3), axis=1)
M

array([[ 5., -2.,  3.,  1.,  0.,  0.],
       [-2.,  1.,  0.,  0.,  1.,  0.],
       [ 3.,  0.,  9.,  0.,  0.,  1.]])

We can now use the following row operations to check if $B$ is row equivalent to identity matrix 

In [14]:
# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing row1 by the sum of itself and a multiple of row2 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [15]:
M1 = swap(M, 0, 1)
M1

array([[-2.,  1.,  0.,  0.,  1.,  0.],
       [ 5., -2.,  3.,  1.,  0.,  0.],
       [ 3.,  0.,  9.,  0.,  0.,  1.]])

In [16]:
M2 = scale(M1, 0, -1/2)
M2

array([[ 1. , -0.5, -0. , -0. , -0.5, -0. ],
       [ 5. , -2. ,  3. ,  1. ,  0. ,  0. ],
       [ 3. ,  0. ,  9. ,  0. ,  0. ,  1. ]])

In [17]:
M3 = replace(M2, 1, 0, -5)
M3

array([[ 1. , -0.5, -0. , -0. , -0.5, -0. ],
       [ 0. ,  0.5,  3. ,  1. ,  2.5,  0. ],
       [ 3. ,  0. ,  9. ,  0. ,  0. ,  1. ]])

In [18]:
M4 = replace(M3, 2, 0, -3)
M4

array([[ 1. , -0.5, -0. , -0. , -0.5, -0. ],
       [ 0. ,  0.5,  3. ,  1. ,  2.5,  0. ],
       [ 0. ,  1.5,  9. ,  0. ,  1.5,  1. ]])

In [19]:
M5 = scale(M4, 1, 2)
M5

array([[ 1. , -0.5, -0. , -0. , -0.5, -0. ],
       [ 0. ,  1. ,  6. ,  2. ,  5. ,  0. ],
       [ 0. ,  1.5,  9. ,  0. ,  1.5,  1. ]])

In [20]:
M6 = replace(M5, 2, 1, -1.5)
M6

array([[ 1. , -0.5, -0. , -0. , -0.5, -0. ],
       [ 0. ,  1. ,  6. ,  2. ,  5. ,  0. ],
       [ 0. ,  0. ,  0. , -3. , -6. ,  1. ]])

From this we can see that it is impossible to get an identity matrix on the left side and, thus, $AA^T$ is not invirtibe.

(C): 

Let's compute $A^TA$

In [24]:
C = A_T @ A
C

array([[10,  2],
       [ 2,  5]])

The determinant of $C$ is $50 - 4 = 46$, not zero, and therefore, $C$ is invertible.

2. The trace is invariant under cyclic permutations, i.e., for three matrices we have $Tr(ABC) = Tr(BCA) = Tr(CAB)$, where $A$ is an $n\times p$ matrix, $B$ is a $p\times m$ matrix, and $C$ is an $m \times n$ matrix. 

Using Example 9, generate three matrices $A$, $B$, and $C$ such that the product $ABC$ makes sense, and verify that:

$$Tr(ABC) = Tr(BCA) = Tr(CAB)$$


__Solution__

In [21]:
# generate a 5x3 matrix
A = np.random.rand(5, 3)

# generate a 3x2 matrix
B = np.random.rand(3, 2)


# generate a 2x5 matrix
C = np.random.rand(2, 5)

# find ABC
ABC = A @ B @ C

print('ABC = \n \n ', ABC)

# find BCA

BCA = B @ C @ A

print('\n BCA = \n \n ', BCA)

# find CAB

CAB = C @ A @ B

print('\n CAB = \n \n ', CAB)

#trace of ABC

Tr_ABC = np.trace(ABC)
print('\n Tr(ABC) = ', Tr_ABC)

Tr_BCA = np.trace(BCA)
print('\n Tr(BCA) = ', Tr_BCA)

Tr_CAB = np.trace(CAB)
print('\n Tr(CAB) = ', Tr_CAB)

ABC = 
 
  [[0.82236106 0.20460274 0.5796988  0.58873788 0.42181421]
 [0.56279345 0.1465404  0.40952237 0.39494344 0.28369911]
 [1.3829235  0.29059356 0.86984786 1.05541697 0.75016112]
 [1.36186643 0.31175002 0.90683238 1.00807812 0.71921338]
 [1.14570643 0.26657129 0.7713465  0.84281257 0.60177285]]

 BCA = 
 
  [[1.27748662 0.62507562 2.19470772]
 [0.79295844 0.38404842 1.5199229 ]
 [1.05323959 0.51591191 1.78706525]]

 CAB = 
 
  [[1.77778664 1.76183804]
 [1.76055928 1.67081365]]

 Tr(ABC) =  3.4486002897305266

 Tr(BCA) =  3.4486002897305266

 Tr(CAB) =  3.4486002897305266


## 2.1 Determinant

1. Let $A$ be an $n\times n$ matrix such that $A^2 = I_n$. Show that $det(A) = \pm 1$.

__Solution:__

By Theorem 4, part (2), $\text{det}(AA) = \text{det}(A) \cdot \text{det}(A) = \text{det}(A)^{2}$. Theorem 1, we have $\text{det}(I_n) = 1$. Therefore, 

$$
\text{det}(A)^{2} = 1
$$

Which means

$$
\text{det}(A) = \pm 1
$$

2. Find the determinant of $A = \begin{bmatrix} 1 & 1 & 2 \\ 2 & 0 & 3 \\ 5 & -3 & 8 \end{bmatrix}$ using the row reduction method. Is $A$ invertible?

__Solution:__



In [22]:
A = np.array([[1,1,2], [2,0,3], [5,-3,8]])

# Elementry row operations:

# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row1 by the sum of itself and a multiple of row2 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [23]:
A

array([[ 1,  1,  2],
       [ 2,  0,  3],
       [ 5, -3,  8]])

In [24]:
A1 = replace(A, 1, 0, -2)
A1

array([[ 1.,  1.,  2.],
       [ 0., -2., -1.],
       [ 5., -3.,  8.]])

In [25]:
A2 = replace(A1, 2, 0, -5)
A2

array([[ 1.,  1.,  2.],
       [ 0., -2., -1.],
       [ 0., -8., -2.]])

In [26]:
A3 = replace(A2, 2, 1, -4)
A3

array([[ 1.,  1.,  2.],
       [ 0., -2., -1.],
       [ 0.,  0.,  2.]])

$A_3$ is already an uppertriangular matrix and we have 

$$\text{det}(A_3) = -4$$

Since we havent used any swap operations we get:

$$\text{det}(A) = \text{det}(A_3) = -4$$

3. Use determinants to decide if the set $\left\lbrace \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}, \begin{bmatrix} 7 \\ 8 \\ 9 \end{bmatrix} \right\rbrace$ is linearly independent.

__Solution:__

A matrix A is invertible if and only if $\text{det}(A)\neq 0$ (Theorem 3). By the invertible matrix theorem, we know that A is invertible if and only if the columns of A are linearly independent.

In [31]:
# matrix A
A = np.array([[1,4, 7], [2,5,8], [3,6,9]])


# Compute a 2x2 determinant
def det2(matrix):
    
    if matrix.shape == (2, 2):
        return matrix[0,0] * matrix[1,1] - matrix[0,1] * matrix[1,0]
    else:
        print("Please enter a 2x2 matrix")

# Computes the determinant of an nxn matrix.
def det(matrix):
    n = matrix.shape[0]
    if n == 1:
        return matrix[0, 0]
    elif n == 2:
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
    else:
        det = 0
        for j in range(n):
            submatrix = np.delete( (np.delete(matrix, 0 , 0)), j ,1)   
            det += (-1) ** (0 + j) * matrix[0, j] * det2(submatrix)
        return det
    
print('det(A) = ', det(A))    

det(A) =  0


Therefore,  $\left\lbrace \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}, \begin{bmatrix} 7 \\ 8 \\ 9 \end{bmatrix} \right\rbrace$ is not linearly independent.




4. Suppose $A$, $B$, $P$ are $n\times n$ matrices, $P$ is invertible, and $r$ is a real number. Mark True or False:

   a. $det(A+B) = det(A) + det(B)$.
   
   b. $det(rA) = r \cdot det(A)$.
   
   c. $det(PAP^{-1}) = det(A)$.
   
__Solution__   


a. False. For example, consider matrices:

$$A = \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix} \quad \text{and} \quad B = \begin{bmatrix} 1 & 0 \\ 0 & 3 \end{bmatrix} 
$$.


Clearly, $\text{det}(A) = 2$, $\text{det}(B) = 3$, and $\text{det}(A+B) = 10$.

b. False. For example, let $A = \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix}$ and $r = 2$. Then, $\text{det}(2A) = 8$, whereas $2\text{det}(A) = 4$.

c. True. Using the invertibility of $P$ and the properties of determinant, we have

$$
\text{det}(PAP^{-1}) = \text{det}(P) \cdot \text{det}(A \cdot P^{-1}) = \text{det}(A \cdot P^{-1}) \cdot \text{det}(P) = \text{det}(A \cdot P^{-1} \cdot P) = \text{det}(A)
$$

5. Determine if the following points are coplanar (i.e., they lie on the same plane):

   $$\begin{bmatrix} 1 \\ 0 \\ 2 \end{bmatrix}, \begin{bmatrix} 4 \\ 3 \\ 5 \end{bmatrix}, \begin{bmatrix} 3 \\ 0 \\ 6 \end{bmatrix}$$
   
__Solution:__



In [32]:
A = np.array([[1,4,3], [0,3,0], [2,5,6]])
A

array([[1, 4, 3],
       [0, 3, 0],
       [2, 5, 6]])

In [33]:
print('det(A) = ', det(A))

det(A) =  0


So the aforementioned points are coplanar. 