# 3.1 Subspaces of $\mathbb{R}^n$

This section focuses on subsets of $\mathbb{R}^n$ that preserve $\mathbb{R}^n$'s linear structure. We will see that any matrix $m\times n$ matrix $A$ admits two important subspaces that contain useful information about the solution set of $A\vec{x} = \vec{b}$ for some $\vec{b}\in \mathbb{R}^m$ 

## Column space and null space

A __subspace__ of $\mathbb{R}^n$ is a subset $H \subset \mathbb{R}^n$ that is closed under addition and scalar multiplication in the following sense:

1. $\vec{u} + \vec{v} \in H \quad \forall \vec{u}, \vec{v} \in H$.
2. $r\vec{u} \in H \quad \forall \vec{u} \in H$ and $\forall r \in \mathbb{R}$.

Note that we can choose $c = 0$, which implies $\vec{0}$ is an element of any subspace. The smallest subspaces of $\mathbb{R}^n$ is $H = \{\vec{0}\}$ and the largest possible subspace of $\mathbb{R}^n$ is itself. Other subspaces of $\mathbb{R}^n$ are lines, planes, and their $n$-dimentional counterparts ($n\geq 3$) that pass through the origin.

__Example 1__

Let $\vec{u}, \vec{v} \in \mathbb{R}^2$. Show that $H := \text{span}(\vec{u}, \vec{v})$ is a subspace of $\mathbb{R}^2$. 

__Solution:__ 

Recall that the span of a set of vectors is the set of all possible linear combinations of those vectors. Let $\vec{x}, \vec{y} \in \text{span}(\vec{u}, \vec{v})$ and $r \in \mathbb{R}$. There exist $c_1, c_2, d_1, d_2 \in \mathbb{R}$ such that $\vec{x} = c_1 \vec{u} + c_2 \vec{v}$ and $\vec{y} = d_1 \vec{u} + d_2 \vec{v}$. We have: 

$$
\vec{x} + \vec{y} = (c_1 + d_1)\ \vec{u} + (c_2 + d_2)\ \vec{v} \quad \text{and} \quad  r\vec{x} = (rc_1)\ \vec{u} + (rc_2)\ \vec{v}
$$

Both of these vectors are in $H$. 

In general, if $\vec{u}_1, \vec{u}_2, \dots, \vec{u}_p \in \mathbb{R}^n$, then the span of of  $\vec{u}_1, \vec{u}_2, \dots, \vec{u}_p$, is a subspace $H\subset \mathbb{R}^n$, and we say H is __spanned (or generated)__ by $\vec{u}_1, \vec{u}_2, \dots, \vec{u}_p$.

Any $m \times n$ matrix $A is associated with important subspaces:

1. The __column space__ of $A$, denoted by $\text{col}(A)$, is the span of the columns of $A$: 

$$
col (A) = \text{span}(\{ \vec{a}_1, \vec{a}_2, \dots, \vec{a}_n\})
$$

where $\vec{v_i}$s are the columns of $A$ for $i = 1,2,\dots, n$. By definition, $col (A)$ is a subspace of $\mathbb{R}^m$.




2. The __null space__ $A$, denoted by $null (A)$, is the solution set of the homogeneous equation $A\vec{x} = \vec{0}$:

$$
null(A) = \{\vec{x}: \ A\vec{x} = \vec{0}\}
$$

By Theorem 2 in subsection 1.2, $\text{null}(A)$ is a subspace of $\mathbb{R}^n$.


__Example 2__

Let $A = \begin{bmatrix} 1 & -1 \\ 2 & 1 \\ -1 & 3 \\ \end{bmatrix}$.

1. Find $col(A)$ and $null(A)$.
2. Is $\vec{b} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \in \text{col}(A)$?
3. Is $\vec{u} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} \in \text{null}(A)$?

__Solution:__

1. $col(A) = \text{span} \left\lbrace\ \begin{bmatrix} 1\\ 2\\ -1 \end{bmatrix}, \begin{bmatrix} -1\\ 1\\ 3\end{bmatrix}\ \right\rbrace $.

To find $null(A)$, we solve the homogeneous equation $A\vec{x} = \vec{0}$. Let's set up the augmented matrix $[A \ | \ \vec{0}]$ and row-reduce it:

In [4]:
import numpy as np

M = np.array([[1, -1, 0], [2, 1, 0], [-1, 3, 0]])
M

array([[ 1, -1,  0],
       [ 2,  1,  0],
       [-1,  3,  0]])

In [5]:
# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row by the sum of itself and a multiple of another 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix 

In [6]:
M1 = replace(M, 1, 0, -2)
M1

array([[ 1., -1.,  0.],
       [ 0.,  3.,  0.],
       [-1.,  3.,  0.]])

In [7]:
M2 = replace(M1, 2, 0, 1)
M2

array([[ 1., -1.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  2.,  0.]])

In [8]:
M3 = scale(M2, 1, 1/3)
M3

array([[ 1., -1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  2.,  0.]])

In [9]:
M4 = replace(M3, 2, 1, -2)
M4

array([[ 1., -1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

Therefore, 

$$\begin{bmatrix} 1 & -1 & | & 0 \\ 2 & 1 & | & 0 \\ -1 & 3 & | & 0 \end{bmatrix} \Rightarrow \begin{bmatrix} 1 & -1 & | & 0 \\ 0 & 1 & | & 0 \\ 0 & 0 & | & 0 \end{bmatrix}.$$

From the row-reduced form, we can see that all columns are pivot and there is no free variable. In other words, the only solution to the system is the trivial solution: $null(A)=0$

2. $\vec{b} \in \text{col}(A)$ if and only if $\vec{b}$ is a linear combination of the columns of $A$. In other words, if and only if the equation $A\vec{x} = \vec{b}$ has a solution. Let's set up the augmented matrix $[A \ | \ \vec{b}]$ and row-reduce it:

In [10]:
import numpy as np

M = np.array([[1, -1, 1], [2, 1, 2], [-1, 3, 1]])
M

array([[ 1, -1,  1],
       [ 2,  1,  2],
       [-1,  3,  1]])

In [11]:
M1 = replace(M, 1, 0, -2)
M1

array([[ 1., -1.,  1.],
       [ 0.,  3.,  0.],
       [-1.,  3.,  1.]])

In [12]:
M2 = replace(M1, 2, 0, 1)
M2

array([[ 1., -1.,  1.],
       [ 0.,  3.,  0.],
       [ 0.,  2.,  2.]])

In [13]:
M3 = scale(M2, 1, 1/3)
M3

array([[ 1., -1.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  2.,  2.]])

In [14]:
M4 = replace(M3, 2, 1, -2)
M4

array([[ 1., -1.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  2.]])

Clearly, the last two rows show that the system is inconsistent. Thus, $\vec{b}$ is not in $\text{col}(A)$.

3. No, $null(A)$ is trivial. We can verify this directly:

$\vec{u} \in \text{null}(A)$ if and only if $A\vec{u} = \vec{0}$:

In [43]:
A = np.array([[1, -1], [2, 1], [-1, 3]])
A

array([[ 1, -1],
       [ 2,  1],
       [-1,  3]])

In [44]:
u = np.array([[1],[1]])
u

array([[1],
       [1]])

In [45]:
#computing Au

Au = A @ u
Au

array([[0],
       [3],
       [2]])

Thus, $\vec{u}$ is not in $null(A)$.


__Example 4__

Suppose $A$ is an invertible $n\times n$ matrix. Then, by the Invertible Matrix Theorem (Theorem 4 in section 2.1), we have the following:

1. $col(A) = \mathbb{R}^n$
2. $null(A) = \{0\}$

## Basis, Dimension, and Rank


Let $H \subset \mathbb{R}^n$ be a subspace. A __basis__ for $H$ is a linearly independent set in $H$ that spans $H$.

According to the Invertible Matrix Theorem (Theorem 4 in section 2.1), the columns of an invertible $n\times n$ matrix form a linearly independent set that spans $\mathbb{R}^n$. Thus, the column space of any invertible matrix is a basis for $\mathbb{R}^n$. It's important to note that bases are not unique.

__Example 6 (The Standard Basis)__

Let $I_n = \begin{bmatrix} \vec{e}_1 & \vec{e}_2 & \dots & \vec{e}_n \end{bmatrix}$ be the identity matrix. The columns of $I_n$, denoted by $\vec{e}_1, \vec{e}_2, \dots, \vec{e}_n$, form a basis for $\mathbb{R}^n$, which is called the standard basis of $\mathbb{R}^n$. For instance, the standard basis elements for $\mathbb{R}^3$ are 

$$
 \vec{e_1} = \begin{bmatrix} 1 \\ 0 \\ 0   \end{bmatrix}, \vec{e_2} = \ \begin{bmatrix} 0 \\ 1 \\ 0   \end{bmatrix},\ \vec{e_3} = \begin{bmatrix} 0 \\ 0 \\ 1   \end{bmatrix}
$$
The following cell computes the standard basis of $\mathbb{R}^4$

In [30]:
#the 4x4 identity matrix
I = np.eye(4)

print(' e1 = \n', np.array([I[0]]).T, '\n')
print(' e2 = \n', np.array([I[1]]).T, '\n')
print(' e3 = \n', np.array([I[2]]).T, '\n')
print(' e4 = \n', np.array([I[3]]).T, '\n')


 e1 = 
 [[1.]
 [0.]
 [0.]
 [0.]] 

 e2 = 
 [[0.]
 [1.]
 [0.]
 [0.]] 

 e3 = 
 [[0.]
 [0.]
 [1.]
 [0.]] 

 e4 = 
 [[0.]
 [0.]
 [0.]
 [1.]] 



__A basis for col A__

The column space of a matrix $A$ is generated by the set of all columns of $A$. If $A$ is invirtible, by invirtible matrix theorem, the columns are all pivot columns and form a linearly independent set and therefore, a basis for col $A$. In general we have:  

__Theorem 1__

The pivot columns of a matrix $A$ form a basis for $col(A)$.

__Example 7__

Suppose $A = \begin{bmatrix} 1 & 3 & 3 & 2 & -9 \\ -2 & -2 & 2 & -8 & 2 \\ 2 & 3 & 0 & 7 & 1 \\ 3 & 4 & -1 & 11 & 8 \end{bmatrix}$.

1. Find a basis for $col(A)$.
2. Find a basis for $null(A)$.

__Solution__

1. We reduce $A$ to its reduced row echelon form (RREF) to find its pivot columns:

In [31]:
A = np.array([[1,3,3,2,-9], [-2,-2,2,-8,2], [2,3,0,7,1], [3,4,-1,11,8]])
A

array([[ 1,  3,  3,  2, -9],
       [-2, -2,  2, -8,  2],
       [ 2,  3,  0,  7,  1],
       [ 3,  4, -1, 11,  8]])

In [32]:
A1 = replace(A, 1, 0, 2)
A2 = replace(A1, 2, 0, -2)
A3 = replace(A2, 3, 0, -3)
A4 = scale(A3, 1, 1/4)
A5 = replace(A4, 2, 1, 3)
A6 = replace(A5, 3, 1, 5)
A7 = scale(A6, 2, 1/7)
A8 = replace(A7, 0, 1, -3)
A9 = replace(A8, 3, 2, -15)
A10 = replace(A9, 1, 2, 4)
A11 = replace(A10, 0, 2, -3)
A11

array([[ 1.,  0., -3.,  5.,  0.],
       [ 0.,  1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])

We can see from the RREF of $A$ that $A$ has 3 pivot columns, which are the first two columns and the last column. Therefore, a basis for $\text{col}(A)$ is the set consisting of the first two columns and the last column of $A$:

$$
\left\lbrace \begin{bmatrix} 1 \\ -2 \\ 2 \\ 3 \end{bmatrix}, \begin{bmatrix} 3 \\ -2 \\ 3 \\ 4 \end{bmatrix}, \begin{bmatrix} -9 \\ 2 \\ 1 \\ 8 \end{bmatrix} \right\rbrace
$$

It's important to note that the columns of the RREF of $A$ are not necessarily in $\text{col}(A)$, and we cannot use them to form a basis for $\text{col}(A)$.

2. To find a basis for $\text{null}(A)$, we solve $A\vec{x}=0$ in the usual manner. Let's form the augmented matrix $[A \ | \ \vec{0}]$:

In [34]:
A0 = np.array([[1,3,3,2,-9,0], [-2,-2,2,-8,2,0], [2,3,0,7,1,0], [3,4,-1,11,8,0]])
A1 = replace(A0, 1, 0, 2)
A2 = replace(A1, 2, 0, -2)
A3 = replace(A2, 3, 0, -3)
A4 = scale(A3, 1, 1/4)
A5 = replace(A4, 2, 1, 3)
A6 = replace(A5, 3, 1, 5)
A7 = scale(A6, 2, 1/7)
A8 = replace(A7, 0, 1, -3)
A9 = replace(A8, 3, 2, -15)
A10 = replace(A9, 1, 2, 4)
A11 = replace(A10, 0, 2, -3)
A11

array([[ 1.,  0., -3.,  5.,  0.,  0.],
       [ 0.,  1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

From this we can see that the general solution is:


$$
\begin{bmatrix}x_1\\ x_2\\x_3\\ x_4\\ x_5 \end{bmatrix} = \begin{bmatrix} 3x_3 - 5x_4 \\ -2x_3 +x_4 \\x_3\\ x_4\\ 0\end{bmatrix} = x_3\begin{bmatrix} 3\\ -2\\ 1\\ 0\\ 0\end{bmatrix} + x_4 \begin{bmatrix} - 5 \\  1 \\0\\ 1\\ 0\end{bmatrix} = span(\ \begin{bmatrix} 3\\ -2\\ 1\\ 0\\ 0\end{bmatrix}, \begin{bmatrix} - 5 \\  1 \\0\\ 1\\ 0\end{bmatrix}\ )
$$

It is also clear that $\begin{bmatrix} 3\\ -2\\ 1\\ 0\\ 0\end{bmatrix}$ and $\begin{bmatrix} - 5 \\  1 \\0\\ 1\\ 0\end{bmatrix}$ are linearly independent. So they form a basis for $null(A)$.


Note that a subspace $H$ can have different bases. For example, the following sets are both bases for $\mathbb{R}^2$:


$$ B = \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix}   \right\}\quad  \text{and} \quad G = \left\{ \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \begin{bmatrix} 2 \\ 1 \end{bmatrix}   \right\}
$$

However, all bases have something in common: 


__Theorem 2__

 All bases of a subspace $H$ in $\mathbb{R}^n$ have the same number of vectors.

The __dimension__ of a subspace $H$, denoted as $dim(H)$, is the number of vectors in any of its bases. Furthermore, we define $dim(\{\vec{0}\})$ to be $0$. The dimension of the column space of a matrix $A$, denoted as $rank(A)$, is referred to as the __rank__ of $A$.

__Example 8__

Show that $dim(\mathbb{R}^n) = n$.

__Solution:__

 We can use Example 6, where it was shown that the columns of the identity matrix $I_n$, denoted as $\{\vec{e}_1, \dots, \vec{e}_n\}$, form a basis for $\mathbb{R}^n$. 

Since there are $n$ columns in the identity matrix $I_n$, the dimension of $\mathbb{R}^n$ is equal to $n$. Hence, $dim(\mathbb{R}^n) = n$.

__Example 9__

Find the rank of subspaces of $\mathbb{R}^3$.

__Solution:__

In $\mathbb{R}^3$, we have the following subspaces:

1. The zero subspace $\{\vec{0}\}$, which has zero dimension.

2. Lines passing through the origin, which have one dimension: every line in $\mathbb{R}^3$ can be spanned by a vector.

3. Planes passing through the origin, which have two dimensions: every plane in $\mathbb{R}^3$ can be spanned by two linearly independent vectors.

4. The entire space $\mathbb{R}^3$, which has three dimensions.


 The next Theorem states that the sum of the dimensions of the column space and null space is equal to the number of columns in the matrix. Additionally, it provides a way to determine the dimensions of the column space and null space based on the number of pivot and non-pivot columns in the matrix, respectively.

__Theorem 3 (Rank-Nulity Theorem)__


If $A$ be an $m \times n$ matrix, then $dim(col(A)) + dim(null(A)) = n$. Moreover, 


1. $dim(col(A)) =$ the number of pivot columns of $A$.

2. $dim(null(A)) =$ the number of non-pivot columns of $A$.


__Example 10__ 

Find the rank and dimension of $null(A)$, where $A = \begin{bmatrix} 1 & 3 &3 & 2 &-9 \\ -2 & -2 & 2 & -8 &2 \\ 2 & 3 &0 & 7 & 1 \\ 3 & 4 & -1 & 11 & 8 \end{bmatrix}$


__Solution__ 

From the solution of Example 7, We know that the RREF of $A$ is 

In [35]:
A11

array([[ 1.,  0., -3.,  5.,  0.,  0.],
       [ 0.,  1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

Which has three pivot columns and two non-pivot columns. Therefore, $rank(A) = 3$ and $dim(null(A)) = 2$



## Excercies:



1. Determine which one of the follwing sets are a subspace:

    a.   $H = \left\lbrace \  \begin{bmatrix} x \\ y \\ z \end{bmatrix} \in \mathbb{R}^3 \mbox{ with } x \geq 0, \right\rbrace.$
    
    b. $H = \left\lbrace \ \begin{bmatrix}
x \\ 1 \\2x 
\end{bmatrix} \in \mathbb{R}^3 \right\rbrace.$


2. Let $A = \begin{bmatrix} 1 & 2 &-9 \\ -2 & -2 & 2 \\ 2 & 3 &0 \end{bmatrix}$.  Find the dimension of $col(A)$ and $null(A)$.


3. Suppose $A$ is a $5 \times 5$ matrix, and $A$ has 3 pivot columns. 

    a. Prove that $A\vec{x}=\vec{0}$ must have nontrivial solutions.
    
    b. Is there an example of $A$ where $col(A)= null(A)$?

 
4. Find an explicit example of a $4\times 4$ matrix $A$ which has $colA = null(A)$ 