# 3.3 Kernel and Image of linear transformations

In this section we show that how existence and uniqueness of solutions for a linear system can be redefined in terms of linear transformations. 

## Kernel and Image

Every linear map $T: \mathbb{R}^n \to \mathbb{R}^m$ has two important associated subspaces:

1. __Kernel of $T$:__ It is the set of all vectors $\vec{x} \in \mathbb{R}^n$ that are mapped to the zero vector by $T$:

$$
\text{Ker}(T) := \{\vec{x} \in \mathbb{R}^n : T(\vec{x}) = 0 \} \subset \mathbb{R}^n.
$$

2. __Image of $T$:__ It is the set of all possible vectors $\vec{y} \in \mathbb{R}^m$ that can be produced by applying $T$ to some vector $\vec{x} \in \mathbb{R}^n$:

$$
\text{Im}(T) := \{\vec{y} \in \mathbb{R}^m : \exists \vec{x} \in \mathbb{R}^n \text{ such that } T(\vec{x}) = \vec{y} \}.
$$

Moreover, if $A$ is the standard matrix representation of $T$, then the kernel of $T$ is equal to the null space of matrix $A$, and the image of $T$ is equal to the column space of matrix $A$:


$$
Ker(T) := null(A) \quad \text{and} \quad Im(T) = col(A).
$$


A mapping $T: \mathbb{R}^n\to \mathbb{R}^m$ is called:

- __onto__ if each $\vec{b}\in \mathbb{R}^m$ is the image of at least one $\vec{x}\in \mathbb{R}^n$.
- __one-to-one__ if each $\vec{b}\in \mathbb{R}^m$ is the image of at most one $\vec{x}\in \mathbb{R}^n$.




Now we are ready to state the main theorems of this section:


__Theorem 1:__ 

A linear transformation $T: \mathbb{R}^n \to \mathbb{R}^m$ is one-to-one if and only if the equation $T(\vec{x}) = \vec{0}$ has only the trivial solution (i.e., $\vec{x} = \vec{0}$).




__Theorem 2:__ 

Let $T: \mathbb{R}^n\to \mathbb{R}^m$ be a linear transformation, and let $A$ be its standard matrix representation. Then:

1. $T$ is one-to-one if and only if the columns of $A$ form a linearly independent set (i.e., every column is a pivot column). This implies that the equation $Ax=b$ has either no solution or a unique solution.

2. $T$ is onto if and only if the columns of $A$ span the entire $\mathbb{R}^m$ space (i.e., $A$ has a pivot in every row). This implies that the equation $A\vec{x} = \vec{b}$ has a solution for every $\vec{b} \in \mathbb{R}^m$.

3. $T$ is both one-to-one and onto if and only if the equation $A\vec{x} = \vec{b}$ has a unique solution for every $\vec{b}\in \mathbb{R}^m$.

__Example 6:__

Consider the linear transformation $T: \mathbb{R}^2 \rightarrow \mathbb{R}^2$ defined as follows: $T\left(\vec{x}\right)$ first reflects $\vec{x}$ across the $x$-axis and then rotates it $90^\circ$ counterclockwise.

1. Determine if $T$ is one-to-one.

2. Determine if $T$ is onto.

3. Compute $T\left(\begin{bmatrix} 1 \\ 2 \end{bmatrix}\right)$.

__Solution:__

(1) 

We first find the standard matrix representation of $T$:

$T$ reflects $\begin{bmatrix} 1 \\ 0 \end{bmatrix}$ to itself and then rotates it to $\begin{bmatrix} 0 \\ 1 \end{bmatrix}$.

$T$ reflects $\begin{bmatrix} 0 \\ 1 \end{bmatrix}$ to $\begin{bmatrix} 0 \\ -1 \end{bmatrix}$ and then rotates it to $\begin{bmatrix} 1 \\ 0 \end{bmatrix}$.

Therefore, the standard matrix of $T$ is $\begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$. Since the columns of $A$ form a linearly independent set, $T$ is both one-to-one and onto.

In [20]:
#(4):

import numpy as np

# the standard matrix of  𝑇 
D = np.array([[0,1],[1,0]]) 

v = np.array([[1],[2]])
w = D @ v 

print(w)

[[2]
 [1]]


## Composition of Linear Maps

The composition of functions is the process of combining two or more functions into a single function. For example, suppose $f: X\to Y$ and $g: Y\to Z$ are two functions. The composition of $f$ and $g$ is a function $h: X \to Z$ defined as $h(x) = g(f(x))$.

Interestingly, when it comes to linear maps, the composition of two linear maps is also a linear map. The following theorem establishes the relationship between matrix product and the composition of linear maps


__Theorem 3__

Let $T: \mathbb{R}^n \to \mathbb{R}^m$ and $S: \mathbb{R}^m \to \mathbb{R}^p$ be linear maps with matrix representations $A$ and $B$, respectively. Then, the composition of $S$ and $T$, denoted as $S \circ T$, is a linear map from $\mathbb{R}^n$ to $\mathbb{R}^p$, and its matrix representation is given by the matrix product $BA$.

In other words, for any vector $\vec{x}$ in $\mathbb{R}^n$, applying $T$ to $\vec{x}$ and subsequently applying $S$ to the result is equivalent to applying the composite map $S \circ T$ to $\vec{x}$. Mathematically, this can be expressed as:

$$ 
S(T(\mathbf{x})) = BA\mathbf{x}
$$

Here, the matrix product $BA$ represents the composite map $S \circ T$ and the original linear maps $T$ and $S$.

__Example 7__

Let $T: \mathbb{R^{3}}\to \mathbb{R}^3$ be the linear map defined in Example 3. 

   a. Show that $T(T(\vec{x})) = T(\vec{x})$ for any $\vec{x}\in \mathbb{R}^3$. 

   b. Compute $T^4(\ \begin{bmatrix} 1 \\ 2 \\ 3\\ \end{bmatrix}\ )$ (where $T^4$ is composition of $T$ with itself 4 times).

__Solution__

a. Intuitively, $T$ does not change points lying on the $xy$-plane and projects the rest onto the $xy$-plane. Therefore, applying $T$ twice to $\mathbf{x}$ should result in the same vector as applying $T$ once. More precisely,

$ T(T(\ \begin{bmatrix} x \\ y \\ z \end{bmatrix}\ )) = T(\ \begin{bmatrix} x \\ y \\ 0 \end{bmatrix}\ ) = \begin{bmatrix} x \\ y \\ 0 \end{bmatrix} = T(\ \begin{bmatrix} x \\ y \\ z \end{bmatrix}\ )$.


b. Using part(a), we can deduce that $T^4 = T^2. Therefore,  T^4(\begin{bmatrix} 1 \\ 2 \\ 3\\ \end{bmatrix}) = T(\begin{bmatrix} 1 \\ 2 \\ 3\\ \end{bmatrix}) = \begin{bmatrix} 1 \\ 2 \\ 0\\ \end{bmatrix}$ 


A linear map $T: \mathbb{R}^n\to \mathbb{R}^n$  is called _invirtible_ if there is a linear transformation $S: \mathbb{R}^n\to \mathbb{R}^n$ such that 

$$
T (S (\vec{x}) = S(T(\vec{x})) = \vec{x} \quad \forall \vec{x}\in \mathbb{R}^n  
$$


__Theorem 4__

For a linear map $T: \mathbb{R}^n \to \mathbb{R}^n$ with $A$ as the standard matrix representation of $T$, the following statements are equivalent:

- $T$ is invertible.
- $T$ is both one-to-one and onto.
- $A$ is invertible and $T^{-1}(\vec{x}) = A^{-1}(\vec{x})$.



__Example 8__

Let $T: \mathbb{R}^3 \to \mathbb{R}^3$ be a linear map defined by:

$$
T(\vec{e}_1) = 2\vec{e}_1 - 3\vec{e}_3, \quad T(\vec{e}_2) = \vec{e}_1 - 2\vec{e}_2 + \vec{e}_3, \quad T(\vec{e}_3) = \vec{e}_2.
$$


1. Show that $\vec{b} = \begin{bmatrix} 1 \\ -2 \\ 3 \end{bmatrix} \in Im(T)$.

2. Compute $T^{-1}(\vec{b})$.


__Solution__

Clearly the matrix representation of $T$ is:

$$
A = \begin{bmatrix} 2 & 1 & 0 \\ 0 & -2 & 1 \\ -3 & 1 & 0 \end{bmatrix}
$$

From this we can see that every column of $A$ is a pivot column and they spann $\mathbb{R}^3$. In other words, $\vec{b}\in col(A) = Im(T)$. To find $T^{-1}(\vec{b})$, we find the inverse of $A$ using row reduction method. Lets set up the augmented matrix $\left[A\ | \ I_3 \right]$

In [21]:
M = np.array([[2,1,0, 1, 0, 0],[0, -2, 1, 0, 1, 0],[-3, 1, 0, 0, 0, 1]])

# Elementry row operations:

# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row by the sum of itself and a multiple of another 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [22]:
M

array([[ 2,  1,  0,  1,  0,  0],
       [ 0, -2,  1,  0,  1,  0],
       [-3,  1,  0,  0,  0,  1]])

In [23]:
M1 = scale(M, 0, 1/2)
M1

array([[ 1. ,  0.5,  0. ,  0.5,  0. ,  0. ],
       [ 0. , -2. ,  1. ,  0. ,  1. ,  0. ],
       [-3. ,  1. ,  0. ,  0. ,  0. ,  1. ]])

In [24]:
M2 = replace(M1, 2, 0, 3)
M2

array([[ 1. ,  0.5,  0. ,  0.5,  0. ,  0. ],
       [ 0. , -2. ,  1. ,  0. ,  1. ,  0. ],
       [ 0. ,  2.5,  0. ,  1.5,  0. ,  1. ]])

In [25]:
M3 = scale(M2, 1, -1/2)
M3

array([[ 1. ,  0.5,  0. ,  0.5,  0. ,  0. ],
       [-0. ,  1. , -0.5, -0. , -0.5, -0. ],
       [ 0. ,  2.5,  0. ,  1.5,  0. ,  1. ]])

In [26]:
M4 = replace(M3, 2, 1, -2.5)
M4

array([[ 1.  ,  0.5 ,  0.  ,  0.5 ,  0.  ,  0.  ],
       [-0.  ,  1.  , -0.5 , -0.  , -0.5 , -0.  ],
       [ 0.  ,  0.  ,  1.25,  1.5 ,  1.25,  1.  ]])

In [27]:
M5 = scale(M4, 2, 1/1.25)
M5

array([[ 1. ,  0.5,  0. ,  0.5,  0. ,  0. ],
       [-0. ,  1. , -0.5, -0. , -0.5, -0. ],
       [ 0. ,  0. ,  1. ,  1.2,  1. ,  0.8]])

In [28]:
M6 = replace(M5, 0, 1, -0.5)
M6

array([[ 1.  ,  0.  ,  0.25,  0.5 ,  0.25,  0.  ],
       [-0.  ,  1.  , -0.5 , -0.  , -0.5 , -0.  ],
       [ 0.  ,  0.  ,  1.  ,  1.2 ,  1.  ,  0.8 ]])

In [29]:
M7 = replace(M6, 0, 2, -0.25)
M7

array([[ 1. ,  0. ,  0. ,  0.2,  0. , -0.2],
       [-0. ,  1. , -0.5, -0. , -0.5, -0. ],
       [ 0. ,  0. ,  1. ,  1.2,  1. ,  0.8]])

In [30]:
M8 = replace(M7, 1,2 , 0.5)
M8

array([[ 1. ,  0. ,  0. ,  0.2,  0. , -0.2],
       [ 0. ,  1. ,  0. ,  0.6,  0. ,  0.4],
       [ 0. ,  0. ,  1. ,  1.2,  1. ,  0.8]])

We can see $A^{-1} = \begin{bmatrix} 0.2 & 0 & -0.2 \\ 0.6 & 0 & 0.4 \\ 1.2 & 1 & 0.8 \end{bmatrix}$. To find $T^{-1} (\vec{b})$, we compute $A^{-1}\vec{b}$. For simplicity we show $A^{-1}$ by $B$:

In [31]:
A_inverse = np.array([[0.2, 0, -0.2], [0.6, 0 , 0.4], [1.2, 1, 0.8]])

b = np.array ([[1], [-2], [3]])

#compute Bb
x = A_inverse @ b
x

array([[-0.4],
       [ 1.8],
       [ 1.6]])

## Exercise

1. Let $T: \mathbb{R}^2 \rightarrow \mathbb{R}^2$ be a linear map given by $T(\vec{x}) =$ first reflect $\vec{x}$ across the $x$-axis and then rotate it $45^\circ$ counterclockwise.

   a. Compute $T \left(T\left(\begin{bmatrix} 1 \\ 2 \end{bmatrix}\right)\right)$.
   
   b. Is $T$ one-to-one?
   
   c. Is $T$ onto?
   
   d. Is $T$ invertible?
   
   e. Solve the equation $T(\vec{x}) = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$.
   
   
   
   
   
2. Let $S$  be the shear transformation given by

$$
S(\vec{x}) = B \vec{x} \quad \text{where} \quad B = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix}
$$ 

and $T$ be the linear transformation described in Exercise 1 above

   a. Compute $(S\circ T)(\begin{bmatrix} 1 \\ -2 \end{bmatrix}))$.
   
   b. Compute $(S \circ T)^{-1} (\begin{bmatrix} 1 \\ -2 \end{bmatrix})$.
   