# 3.5  Answers to Exercises

## 3.1 Subspaces of $\mathbb{R}^n$

1. Determine which one of the follwing sets is a subspace:

    a.   $H = \left\lbrace \  \begin{bmatrix} x \\ y \\ z \end{bmatrix} \in \mathbb{R}^3 \mbox{ with } x \geq 0, \right\rbrace.$
    
    b. $H = \left\lbrace \ \begin{bmatrix}
x \\ 1 \\2x 
\end{bmatrix} \in \mathbb{R}^3 \right\rbrace.$


__Solution__

a. is not a subspace because it is not closed under taking sum. For example, let

$$
 \vec{u} = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}, \quad\text{and} \quad  \vec{v} = \begin{bmatrix} -2 \\ 0 \\ 0 \end{bmatrix}
$$

Then $\vec{u}+ \vec{v}$ is not in $H$.

b. $H$ is not a subspace because $\vec{o}$ is not in $H$. 

 2. Let $A = \begin{bmatrix} 1 & 2 &-9 \\ -2 & -2 & 2 \\ 2 & 3 &0 \end{bmatrix}$.  Find a basis for $col(A)$ and $null(A)$.
 
__Solution:__ 

We use row operation to find the pivot columns of $A$:

In [1]:
import numpy as np

A = np.array([[1,2,-9], [-2,-2,2],[2,3,0]])

# Elementry row operations:

# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row1 by the sum of itself and a multiple of row2 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [2]:
A

array([[ 1,  2, -9],
       [-2, -2,  2],
       [ 2,  3,  0]])

In [3]:
A1 = replace(A, 1, 0, 2)
A1

array([[  1.,   2.,  -9.],
       [  0.,   2., -16.],
       [  2.,   3.,   0.]])

In [4]:
A2 = replace(A1, 2, 0, -2)
A2

array([[  1.,   2.,  -9.],
       [  0.,   2., -16.],
       [  0.,  -1.,  18.]])

In [5]:
A3 = scale(A2, 1, 0.5)
A3

array([[ 1.,  2., -9.],
       [ 0.,  1., -8.],
       [ 0., -1., 18.]])

In [6]:
A4 = replace(A3, 2, 1, 1)
A4

array([[ 1.,  2., -9.],
       [ 0.,  1., -8.],
       [ 0.,  0., 10.]])

From this we can see that all columns are pivots and the columns of $A$ form a basis for $\text{col}(A)$:

$$
\left\{ \ \begin{bmatrix} 1 \\ 2 \\ -9 \end{bmatrix}, \begin{bmatrix}  -2 \\ -2 \\ 2 \end{bmatrix}, \begin{bmatrix} 2 \\ 3 \\ 0 \end{bmatrix}   \  \right\}
$$

Therefore, $dim(\text{col}(A) = 3)$. By Rank-Nulity Theorem, $dim(\text{null}(A) = 0)$, or in other words, $\text{null}(A) = \vec{o}$. We could also form the augmented matrix $[A|0]$ and find the RREF of it:

In [7]:
# zero vector
O = np.array([np.zeros(3)]).T
O

array([[0.],
       [0.],
       [0.]])

In [8]:
# Augmented matrix [A|0]

B = np.concatenate((A, O) , axis = 1)
B

array([[ 1.,  2., -9.,  0.],
       [-2., -2.,  2.,  0.],
       [ 2.,  3.,  0.,  0.]])

In [9]:
B1 = replace(B, 1, 0 , 2)
B1

array([[  1.,   2.,  -9.,   0.],
       [  0.,   2., -16.,   0.],
       [  2.,   3.,   0.,   0.]])

In [10]:
B2 = replace(B1, 2, 0, -2)
B2

array([[  1.,   2.,  -9.,   0.],
       [  0.,   2., -16.,   0.],
       [  0.,  -1.,  18.,   0.]])

In [11]:
B3 = scale(B2, 1, 0.5)
B3

array([[ 1.,  2., -9.,  0.],
       [ 0.,  1., -8.,  0.],
       [ 0., -1., 18.,  0.]])

In [12]:
B4 = replace(B3, 2, 1, 1)
B4

array([[ 1.,  2., -9.,  0.],
       [ 0.,  1., -8.,  0.],
       [ 0.,  0., 10.,  0.]])

In [13]:
B5 = scale(B4, 2, 1/10)
B5

array([[ 1.,  2., -9.,  0.],
       [ 0.,  1., -8.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [14]:
B6 = replace(B5, 0, 1, -2)
B6

array([[ 1.,  0.,  7.,  0.],
       [ 0.,  1., -8.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [15]:
B7 = replace(B6, 0, 2, -7)
B7

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1., -8.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [16]:
B8 = replace(B7, 1, 2, 8)
B8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

3. Suppose $A$ is a $5 \times 5$ matrix, and $A$ has 3 pivot columns. 

    a. Prove that $A\vec{x}=\vec{0}$ must have nontrivial solutions.
    
    b. Is there an example of $A$ where $col(A)= null(A)$?
    
__Solution:__ 


a. By Rank-Nullity Theorem, $dim(\text{null}(A) = 2)$ so it is not trivial.  

b. No it is not. Because in such a matrix we would have 

$$
dim(col(A)) + dim(null(A)) = 5 \quad \text{which implies} \quad dim(col(A)) + dim(col(A)) = 5 \quad \text{or} \quad dim(col(A)) = 2.5
$$
which is not possible.



4. Find an explicit example of a $4\times 4$ matrix $A$ which has $colA = null(A)$ 


__Solution:__

Let 
$$
A = \begin{bmatrix}
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
\end{bmatrix}
$$

Clearly, $\vec{u} = \begin{bmatrix} 0 \\ 0 \\ 1 \\ 0 \end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}$ form a basis for $\text{col}(A)$. We can easily verify that $A\vec{u} = A\vec{v} = \vec{0}$, indicating that $\vec{u}$ and $\vec{v}$ are in $null(A)$. Now, we will show that they also form a basis for $null(A)$.

According to the rank-nullity theorem, we know that $\text{dim}(null(A)) = 2$. Thus, if we show that $\vec{u}$ and $\vec{v}$ are linearly independent, we are done! Fortunately, they are linearly independent because they are not multiples of each other.

## 3.2  Introduction to Linear Transformation


1. Determine if each transformation is linear


   a. $T: \mathbb{R}^2 \rightarrow \mathbb{R}^2$ given by

$$
T\left( \begin{bmatrix} x_1 \\ x_2  \end{bmatrix} \right) = \begin{bmatrix} x_2 \\ -x_1
\end{bmatrix}.
$$



   b. $H: \mathbb{R}^2 \rightarrow \mathbb{R}^2$ given by 
    
$$
T\left( \begin{bmatrix} x_1 \\ x_2  \end{bmatrix} \right) = \begin{bmatrix} (x_1)^2 \\ 0 \end{bmatrix}.
$$

__Solution:__


(a): $T$ is a linear transformation since

$$
T\left( \begin{bmatrix}
x_1 \\ x_2
\end{bmatrix} + \begin{bmatrix}
y_1 \\ y_2
\end{bmatrix} \right) = T\left( \begin{bmatrix}
x_1+y_1 \\ x_2+y_2
\end{bmatrix}  \right) =  \begin{bmatrix}
x_2+y_2 \\ -(x_1+y_1)
\end{bmatrix} =  \begin{bmatrix}
x_2+y_2 \\ -x_1-y_1
\end{bmatrix} = \begin{bmatrix}
x_2  \\ -x_1
\end{bmatrix} +\begin{bmatrix}
y_2  \\ -y_1
\end{bmatrix} =  T\left( \begin{bmatrix}
x_1 \\ x_2
\end{bmatrix}\right) + T\left(\begin{bmatrix}
y_1 \\ y_2
\end{bmatrix} \right)
$$

 and 

$$
T\left( c\begin{bmatrix}
x_1 \\ x_2
\end{bmatrix} \right)  = T\left( \begin{bmatrix}
c x_1 \\ c x_2
\end{bmatrix} \right)  = \begin{bmatrix}
-cx_2 \\ cx_1
\end{bmatrix} = c\begin{bmatrix}
-x_2 \\ x_1
\end{bmatrix} = cT\left( \begin{bmatrix}
x_1 \\ x_2
\end{bmatrix} \right)
$$



(b) $H$ is not a linear transformation because


$$
cT\left( \begin{bmatrix}
x_1 \\ x_2
\end{bmatrix} \right) = c\begin{bmatrix}
(x_1)^2 \\ 0 
\end{bmatrix} =\begin{bmatrix}
c(x_1)^2\\ 0 
\end{bmatrix}
$$

but

$$
T\left( c\begin{bmatrix}
x_1 \\ x_2
\end{bmatrix} \right) = T\left( \begin{bmatrix}
cx_1 \\ cx_2
\end{bmatrix} \right) =
\begin{bmatrix}
(cx_1)^2 \\ 0
\end{bmatrix}= \begin{bmatrix}
(c^2(x_1)^2 \\ 0
\end{bmatrix}.
$$

2. Find the standard matrix of $T: \mathbb{R}^2 \rightarrow \mathbb{R}^2$ given by $T(\vec{x}) =$ first reflect $\vec{x}$ across the $x$-axis and then rotate $45^\circ$ counterclockwise.

__Solution:__


To find the standard matrix representation of $T$ we apply $T$ to the standard basis vectors of $\mathbb{R}^2$:

$T$ reflects $\begin{bmatrix} 1 \\ 0 \end{bmatrix}$ to itself and then rotates it to $\begin{bmatrix} \frac{\sqrt{2}}{2} \\ \frac{\sqrt{2}}{2} \end{bmatrix}$.

$T$ reflects $\begin{bmatrix} 0 \\ 1 \end{bmatrix}$ to $\begin{bmatrix} 0 \\ -1 \end{bmatrix}$ and then rotates it to $\begin{bmatrix} \frac{\sqrt{2}}{2} \\ -\frac{\sqrt{2}}{2} \end{bmatrix}$.

Therefore, the standard matrix of $T$ is $\begin{bmatrix} \frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2} \\ \frac{\sqrt{2}}{2} & - \frac{\sqrt{2}}{2} \end{bmatrix}$.




3. Suppose $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$ is a linear map and 

$$
T\left( \begin{bmatrix} 1 \\ 0 \end{bmatrix} \right) = \begin{bmatrix} 1 \\ 2 \\ 3
\end{bmatrix} \quad \text{and} \quad  T\left( \begin{bmatrix}
0 \\ 1 \end{bmatrix} \right) = \begin{bmatrix} 0 \\ 1 \\ -1 \end{bmatrix}.
$$

Find 
$T \begin{bmatrix}
2 \\ 3
\end{bmatrix}$. 

__Solution__

Note that
$$
\begin{bmatrix}2 \\ 3 \end{bmatrix} = 2 \begin{bmatrix} 1\\ 0 \end{bmatrix} + 3 \begin{bmatrix} 0 \\ 1 \end{bmatrix}.
$$

Now 

$$
T \begin{bmatrix}2 \\ 3 \end{bmatrix} = T \left( 2 \begin{bmatrix} 1\\ 0 \end{bmatrix} + 3 \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right) = 2 T\left(\begin{bmatrix} 1\\ 0 \end{bmatrix}\right) + 3 T\left (\begin{bmatrix} 1\\ 0 \end{bmatrix}\right) = 2 \begin{bmatrix} 1 \\ 2 \\ 3
\end{bmatrix} + 3 \begin{bmatrix} 0 \\ 1 \\ -1 \end{bmatrix} = \begin{bmatrix} 2 \\ 7 \\ 3 \end{bmatrix}
$$

## 3.3 Kernel and Image of linear transformations

1. Let $T: \mathbb{R}^2 \rightarrow \mathbb{R}^2$ be a linear map given by $T(\vec{x}) =$ first reflect $\vec{x}$ across the $x$-axis and then rotate it $45^\circ$ counterclockwise.

   a. Compute $T \left(T\left(\begin{bmatrix} 1 \\ 2 \end{bmatrix}\right)\right)$.
   
   b. Is $T$ one-to-one?
   
   c. Is $T$ onto?
   
   d. Is $T$ invertible?
   
   e. Solve the equation $T(\vec{x}) = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$.
   
   
   
__Solution:__

The standard matrix of $T$ is $A = \begin{bmatrix} \frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2} \\ \frac{\sqrt{2}}{2} & - \frac{\sqrt{2}}{2} \end{bmatrix}$ (see Exercise 2 in the previous section). Since the columns of $A$ are linearly independent $A$, and equivalently $T$, is invirtible and both one-to-one and onto. Note that 


$$
T(\vec{x}) = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \quad \iff \quad \vec{x} = A^{-1} \begin{bmatrix} 1 \\ 2 \end{bmatrix}
$$

We claim $A^{-1} = A$ and therfore 

$\vec{x} = A \begin{bmatrix} 1 \\ 2 \end{bmatrix} = \begin{bmatrix}  2.12132034\\ -0.70710678 \end{bmatrix}$ as computed below:

In [17]:
x = np.array([[1],[2]])
A = np.array([[np.sqrt(2)/2, np.sqrt(2)/2],[np.sqrt(2)/2, - np.sqrt(2)/2]])
A @ x

array([[ 2.12132034],
       [-0.70710678]])

Now let us show $A^{-1} = A$. To do so, we show $A^{2} = I_2$

In [18]:
A @ A

array([[1., 0.],
       [0., 1.]])

We could also compute the inverse directly:

In [19]:
# Compute the inverse
def inverse_matrix(matrix):
    a, b = matrix[0]
    c, d = matrix[1]
    
    det = a * d - b * c

    if det == 0:
        print(matrix, "is not invertible")
    else:
        D = 1 / det    
        inverse = np.zeros((2, 2))
        inverse[0, 0] = D * d
        inverse[0, 1] = -D * b
        inverse[1, 0] = -D * c
        inverse[1, 1] = D * a

        return(inverse)
    
inverse_matrix(A)    

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

2. Let $S$  be the shear transformation given by

$$
S(\vec{x}) = B \vec{x} \quad \text{where} \quad B = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix}
$$ 

and $T$ be the linear transformation described in Exercise 1 above

   a. Compute $(S\circ T)(\begin{bmatrix} 1 \\ -2 \end{bmatrix}))$.
   
   b. Compute $(S \circ T)^{-1} (\begin{bmatrix} 1 \\ -2 \end{bmatrix})$.
   
   
__Solution__ 

(a): 

From Exercise 1 above, we know that the standard matrix representation of $T$ is $A = \begin{bmatrix} \frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2} \\ \frac{\sqrt{2}}{2} & - \frac{\sqrt{2}}{2} \end{bmatrix}$. Note that

$$
S(T(\vec{x})) = BA \vec{x}
$$

So we compute $BA\vec{x}$:

In [22]:
# vector x
x = np.array([[1],[-2]])

# matrix A
A = np.array([[np.sqrt(2)/2, np.sqrt(2)/2],[np.sqrt(2)/2, - np.sqrt(2)/2]])

# matrix B

B = np.array([[1,2],[0,1]])

# computing AB

B @ A @ x

array([[3.53553391],
       [2.12132034]])

(b):

$$(S \circ T)^{-1}) (\vec{x}) = (BA)^{-1} \vec{x}$$

So we compute $A^{-1} B^{-1} \vec{x}$. We already know that $A^{-1} = A$ (from the previous exercise). Lets compute $B^{-1}$ 

In [24]:
# inverse of B    
B_inverse = inverse_matrix(B) 

# computing B^{-1} A^{-1} x

A @ B_inverse @ x

array([[2.12132034],
       [4.94974747]])

## 3.4 Change of basis


1. Let 

$$
P = \begin{bmatrix} 1 & 2 & -1 \\ -3 & -5 & 0 \\ 4 & 6 & 1 \end{bmatrix}
$$

and $B$ be a basis of $\mathbb{R}^3$ containing 

$$
\vec{b_1} = \begin{bmatrix} -2 \\ 2 \\ 3 \end{bmatrix}, \vec{b_2}\begin{bmatrix} -8 \\ 5 \\ 2 \end{bmatrix}, \vec{b_3} = \begin{bmatrix} -7 \\ 2 \\ 6 \end{bmatrix}.
$$

Find a basis $G = \{\vec{g_1}, \vec{g_2}, \vec{g_3}\}$ such that $P$ becomes the transition of basis from $G$ to $B$.

__Solution__

By Theorem 1, the columns of the transition matrix $P_{G\to B}$ are the coordinates of each of the basis vectors in $G$ with respect to the basis $B$:

$$
P_{G\to B} = \begin{bmatrix} 1 & 2 & -1 \\ -3 & -5 & 0 \\ 4 & 6 & 1 \end{bmatrix} = \left[ [\vec{g_1}]_B,\, [\vec{g_2}]_B,\,[\vec{g_3}]_B\right]$$

We know that $\vec{g_i}$s and $[\vec{g_i}]_B$s are related by equation

$$
\vec{g_i} = P_B\ [\vec{g_i}]_B \quad i \leq 3
$$

where $P_B$ is a matrix whose columns are elements of $B$

$$
P_B = \begin{bmatrix} -2 & -8 & -7 \\ 2 & 5 & 2 \\ 3 & 2 & 6 \end{bmatrix}
$$



In [25]:
# P_B
P_B = np.array([[-2,-8,-7], [2,5,2], [3,2,6]])

#P_{GtoB}
P_GtoB = np.array([[1,2,-1],[-3,-5,0],[4,6,1]])

#computing g_1
for i in range(3):
    print('g', i+1, '=', P_B @  P_GtoB[:,i] )

g 1 = [-6 -5 21]
g 2 = [-6 -9 32]
g 3 = [-5  0  3]


2. Consider the following bases of $\mathbb{R}^2$: 

$$
B = \left\lbrace \begin{bmatrix}
3 \\ 2
\end{bmatrix}, \begin{bmatrix}
1 \\ 1
\end{bmatrix}\right\rbrace \quad \text {and} \quad G = \left\lbrace \begin{bmatrix}
-2 \\ -5
\end{bmatrix}, \begin{bmatrix}
1 \\ 2
\end{bmatrix}\right\rbrace
$$ 

   a. For $\vec{x} = \begin{bmatrix} 3 \\ -1 \end{bmatrix}$  compute $[\vec{x}]_{B}.$
   
   b. Let $A = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix}$ be the standard matrix representation of $T: \mathbb{R}^2 \to \mathbb{R}^2$. Find the matrix representation for $T: (\mathbb{R}^2,B) \to (\mathbb{R}^2, G)$.
   
   

__Solution:__

In [20]:
#(a)

x = np.array([[3],[-1]])

# Basis B
B = np.array([[3,2],[1,1]])
P_B = B.T

# compute [x]_B

x_B = np.linalg.inv(P_B) @ x
x_B

array([[ 4.],
       [-9.]])

In [21]:
# (b)

# Standard basis in R^2:
S = np.array([[1,0], [0,1]]) 
P_S = np.transpose(S)

# Basis B
B = np.array([[3,2],[1,1]])
P_B = B.T

# Basis G
G = np.array([[-2,-5],[1,2]])
P_G = G.T



# matrix representation of T with rspect to B1 and G1
A = np.array([[1,2], [0,1]])


#create transtion matrix from B2 to B1
P_BtoS = np.linalg.inv(P_S) @ P_B 

#create the transtion matrix from G1 to G2
P_St0G = np.linalg.inv(P_G) @ P_S 

#computes the representation with respect to new bases
D = P_St0G @ A @ P_BtoS
D

array([[12.,  5.],
       [31., 13.]])