# 4.2 Diagonalization

This section introduces diagonalization and characterizes diagonalizability. Diagonalization is a useful factorization of a matrix $A$ based on its eigenvalue–eigenvector information. This factorization allows us to quickly access properties that are invariant under similarity, such as rank, invertibility, and eigenvalues. It also enables us to calculate powers of $A$ for large $k$, which is a fundamental concept in various applications, including discrete dynamical systems.

## Computing powers of a matrix 

Let's consider the matrix $A = \begin{bmatrix} 7 & 2\\ -4 & 1 \end{bmatrix}$. We wish to compute $A^{k}$ for an arbitrary $k\in \mathbb{N}$, given that $A= PAP^{-1}$, where $P = \begin{bmatrix} 1 & 1\\ -1 & -2 \end{bmatrix}$, and $D = \begin{bmatrix} 5 & 0\\ 0 & 3 \end{bmatrix}$.

Using this decomposition, we have:

$$
A^{k} = (PDP^{-1})(PDP^{-1})\dots (PDP^{-1}) = PD^{k}P.
$$

Since $D$ is diagonal, $D^{k} = \begin{bmatrix} 5^{k} & 0\\ 0 & 3^{k} \end{bmatrix}$. Additionally, $P^{-1} = \begin{bmatrix} 2 & 1\\ -1 & -1 \end{bmatrix}$. Therefore,

$$
A^{k} = \begin{bmatrix} 1 & 1\\ -1 & -2 \end{bmatrix} \begin{bmatrix} 5^{k} & 0\\ 0 & 3^{k}\end{bmatrix} \begin{bmatrix} 2 & 1\\ -1 & -1 \end{bmatrix} = \begin{bmatrix}  2\times 5^{k} -3^{k}& 5^{k}- 3^{k}\\ 2\times 3^{k} - 2\times 5^{k} & 2 \times3^{k} -5^{k}\end{bmatrix}.
$$

This decomposition, known as diagonalization, enables us to compute $A^k$ easily for large values of $k$. Without such factorization, computing $A^k$ for large matrices and large $k$ can be a time-consuming task. Therefore, it is beneficial to find such decomposition before calculating the power of $A$. 

Unfortunately, this decomposition doesn't exist for all matrices. The goal of this section is to characterize matrices that admit such a factorization.

## Diagonalization

An $n \times n$ matrix $A$ is called __diagonalizable__ if it is _similar_ to a diagonal matrix. More precisely, there exists an invertible $n \times n$ matrix $P$ and an $n \times n$ diagonal matrix $D$ such that $A = PDP^{-1}$.

It turns out an $n\times n$ matrix is diagonalizable if we can form a basis $\mathbb{R}^n$ using eigenvectors of $A$:

__Theorem 1__

An $n \times n$ matrix $A$ is diagonalizable if and only if $A$ has $n$ linearly independent eigenvectors.


In fact, suppose $\lambda_1, \lambda_2, \dots, \lambda_n$ are eigenvalues of $A$, and $\{\vec{v_1}, \vec{v}_2, \dots, \vec{v}_n\}$ is the linearly independent set of eigenvectors of $A$. If we form the matrix $P$ by taking the eigenvectors as columns, and $D$ is a diagonal matrix with eigenvalues $\lambda_1, \lambda_2, \dots, \lambda_n$ on the diagonal, then we have $A = PDP^{-1}$.


Finding eigenvectors in general is not an easy task, and is not clear how to check which $n \times n$ matrices have $n$ linearly independent eigenvectors. The next theorem partially addresses this issue.


__Theorem 2__

The eigenvectors corresponding to distinct eigenvalues are linearly independent.

Combining Theorem 1 and Theorem 2, we obtain the following corollary:

__Corollary 1__

An $n \times n$ matrix with $n$ distinct eigenvalues is diagonalizable.



__Example 1__  Is
$
A = \begin{bmatrix} 1 & 3 & 2 \\ -3 & -5 & 3 \\ 3 & 3 & 1 \end{bmatrix}
$
diagonalizable? If yes find a diagonalization for it. 

__Solution__

To determine if $A$ is diagonalizable we need to find eigenvalues and to check if it admits $3$ linearly independent eigenvectors. 

- Step 1 

we use _linalg.eigvas_ to find the eigenvalues and eigenvectors of $A$:


In [1]:
import numpy as np
from numpy import linalg

A = np.array([[1,3,3],[-3,-5,3],[3,3,1]])
# find evalues and evectors
evalues, evectors = linalg.eig(A)

print("eigenvalues = ",  evalues)

eigenvalues =  [-5. -2.  4.]


$A$ has three distintc eigenvalues and therefore it is diagonalizable by Corollary 1.

- Step 2: Constructing the diagonal matrix $D$

In [2]:
lambda_1 = evalues[0]
lambda_2 = evalues[1]
lambda_3 = evalues[2]

D = np.array([[lambda_1, 0, 0], [0, lambda_2, 0], [0, 0, lambda_3]]) 
D

array([[-5.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0.,  4.]])

- Step 3 : Finding the matrix $P$ whose $i$th column is an eigenvector corresponding to $\lambda_{i}$ for $i\in \{1,\ 2,\ 3\}$:

In [3]:
# set up the invirtible matrix P
P = evectors

- Step 4: compute the inverse of matrix P

In [4]:
# compute the inverse of P

Q = linalg.inv(P)

- Step 5 (sanity check): Now that we have $D$, $P$, $Q = P^{-1}$, lets check if $A = PDQ$

In [5]:
P @ D @ Q

array([[ 1.,  3.,  3.],
       [-3., -5.,  3.],
       [ 3.,  3.,  1.]])

__Example 2__  Is
$
A = \begin{bmatrix} 1 & 3 & 2 \\ -3 & -5 & -3 \\ 3 & 3 & 1 \end{bmatrix}
$
diagonalizable? If yes find a diagonalization for it. 

__Solution:__ 

- Step 1:  Finding eigenvalues and eigenvectors of $A$:

In [6]:
A = np.array([[1,3,3],[-3,-5,-3],[3,3,1]])

# find evalues and evectors
evalues, evectors = linalg.eig(A)

print("eigenvalues = ",  evalues)

eigenvalues =  [ 1. -2. -2.]


$A$ has 2 eigenvalues: $\lambda_1 = 1$ with multiplicity 1 and $\lambda_2 = -2$ with multiplicity 2. Note that we cannot use Corollary 1 anymore because eigenvalues are not distinct. To check if $A$ is diagonalizable, we need to find three linearly independet eigenvectors of $A$. Lets have a look at our eigenvectors:

In [7]:
# A matrix whose columns are eigenvectors:
P = evectors

# computes the rank of P
np.linalg.matrix_rank(P)

3

Since $rank(P) = 3$ the columns of $P$ are linearly independents. Thus, $A$ is diagonalizable by Theorem 1. 

- Step 2: Finding the diagonal matrix $D$ 

In [8]:
lambda_1 = evalues[0]
lambda_2 = evalues[1]
lambda_3 = evalues[2]

D = np.array([[lambda_1, 0, 0], [0, lambda_2, 0], [0, 0, lambda_3]]) 
D

array([[ 1.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0., -2.]])

- Step 3: Finding the matrix $P$ whose $i$th column is an eigenvector corresponding to $\lambda_{i}$ for $i\in \{1,\ 2,\ 3\}$. We already have this matrix so we go to the next step.

- Step 4: Computing the inverse of $P$

In [9]:
# computing the inverse of P

Q = np.linalg.inv(P)
Q

array([[ 1.73205081,  1.73205081,  1.73205081],
       [-1.41421356, -1.2786323 ,  0.13558127],
       [ 0.        ,  1.48664829,  1.48664829]])

- Step 5 (sanity check): lets check if $A = PDQ$

In [10]:
# check A = PDQ 
P @ D @ Q

array([[ 1.,  3.,  3.],
       [-3., -5., -3.],
       [ 3.,  3.,  1.]])

The next theorem provides another way to characterize the diagonalizability of matrices based on the multiplicity of eigenvalues. Before stating the theorem, we need the following definition:

Suppose $A$ is a square matrix and $\lambda$ is an eigenvalue of $A$. The dimension of the corresponding eigenspace $E_{\lambda} = null(A -\lambda I)$ is called the __geometric multiplicity of $\lambda$__.

__Theorem 3:__

A square matrix $A$ is diagonalizable if and only if the algebraic multiplicity of each eigenvalue is equal to its geometric multiplicity. More formally, if $\lambda_1, \lambda_2, \dots, \lambda_p$ are eigenvalues of $A$ with algebraic multiplicities $m_1, m_2, \dots, m_p$, respectively, then 

$$
m_i = \text{dim}(E_{\lambda_i}) \quad \forall i \in \{1, 2, \dots, p\}
$$

Recall that dim($E_{\lambda_i}$) = dim null$(A-\lambda_i I)$ = the number of non-pivot columns in $(A-\lambda_{i} I)$

__Example 3:__ 

Is $M = \begin{bmatrix} 1 & 1 & 0 \\ 0 & 1 & 1 \\ 0 & 0 & 2 \end{bmatrix}$ diagonalizable? If yes, find a diagonalization for it.

__Solution:__

$M$ is an upper triangular matrix, and its eigenvalues are on the diagonal: $\lambda_1 = 1$ with algebraic multiplicity 2 and $\lambda_2 = 2$ with algebraic multiplicity 1.

Since we don't have distinct eigenvalues, Corollary 1 doesn't apply here. Let's take a look at our eigenvectors:


In [11]:
import numpy as np
from numpy import linalg


M = np.array([[1, 1, 0], [0, 1, 1], [0, 0, 2]])

evalues, evectors  = np.linalg.eig(M)
p = evectors

np.linalg.matrix_rank(p)

2

Observe that the rank of matrix $P$ is two, which means we don't have three linearly independent eigenvectors in $M$. However, using Theorem 3, we can confirm that this is not the case, and consequently, $M$ is not diagonalizable. In fact, it is straightforward to check that the geometric multiplicity of $\lambda = 1$ is 1 ($\text{dim}(E_1) = 1$), while the algebraic multiplicity is 2. Thus, $M$ is not diagonalizable.


## Diagonalization as a change of basis 

Recall that similar matrices represent the same linear map under two different choices of a pair of bases for $\mathbb{R}^n$ and $\mathbb{R}^m$. More precisely, suppose $A = PCP^{-1}$ ($C$ is not necessarily diagonal), then the matrix representation of $T$ with respect to the basis $B$ (formed by the columns of $P$) is $C$. Conversely, changing the basis of $\mathbb{R}^n$ leads to a matrix representation of $T$ that is similar to $A$ (section 3.4). This particularly applies to diagonalizable matrices because a matrix is diagonalizable if it is similar to a diagonal matrix.

__Theorem 2__ (Diagonal Matrix Representation)

Suppose $T: \mathbb{R}^n \to \mathbb{R}^n$ and $A$ is the standard matrix representation of $T$ that is diagonalizable. Let $A = PDP^{-1}$ be a diagonalization of $A$ where $D$ is an $n\times n$ diagonal matrix, and $P$ is an invertible $n\times n$ matrix. If $B$ is the basis for $\mathbb{R}^n$ formed by the columns of $P$, then $D$ is the matrix representation of the transformation $T: (\mathbb{R}^n, B) \to (\mathbb{R}^n, B)$.

__Example 3__ Let $T: \mathbb{R}^2 \to \mathbb{R}^2$ and $A = \begin{bmatrix} 7 & 2 \\ -4 & 2 \end{bmatrix}$ be the standard matrix representation of $T$. Find a basis $B$ for $T$ such that the matrix representation of $T$ with respect to $B$ is diagonal.

__Solution:__

From Example 1, we know that $A = PAP^{-1}$ where $P = \begin{bmatrix} 1 & 1 \\ -1 & -2 \end{bmatrix}$ and $D = \begin{bmatrix} 5 & 0 \\ 0 & 3 \end{bmatrix}$.

The columns of $P$ are eigenvectors of $A$, and they form a basis $B$ for $\mathbb{R}^2$. By Theorem 2, $D$ is the matrix representation of $T$ with respect to $B$. In fact, the mappings $\vec{x} \to A\vec{x}$ and $\vec{x} \to D\vec{x}$ describe the same linear transformation, relative to different bases.


## Excercises


1. Suppose
$
M = \begin{bmatrix} 2 & 4 & 3 \\ -4 & -6 & -3 \\ 3 & 3 & 1 \end{bmatrix}.
$

    a. Is M diagonalizable? If yes find a diagonalization for it.
    
    b. Use this diagonalization to compute $M^{100}$




2. Suppose $C=\begin{bmatrix}
3 & 0 & 1 & 0 & 0\\
0 & 3 & 0 & 0 & 0\\
0 & 0 & 3 & 0 & 0\\
0 & 0 & 3 & 2 & 0\\
0 & 0 & 0 & 0 & 2
\end{bmatrix}$. Is $C$ diagonalizable?


3. Let $A$ be a $5\times 5$ matrix, with two eigenvalues. One eigenspace is three-dimensional, the other is two dimensional. Is $A$ diagonalizable?


4. Compute $A^{200}$ where $A = \begin{bmatrix} 4 & -3\\ 2 & -1 \end{bmatrix}$. 
