# 4.1 Eigenvalues and Eigenvectors

1. If $\vec{v}$ is an eigenvector of $A$ corresponding to $\lambda$, show that $\lambda^3$ is an eigenvalue of $A^3$.


__Solution:__


$$
A^3\vec{v} = A^{2}A\vec{v} = A^2 \lambda\vec{v} = \lambda A^2 \vec{v} = \lambda A A\vec{v} = \lambda A \lambda \vec{v} = \lambda^2 A \vec{v} = \lambda^{3} \vec{v}
$$



2. If A is an $n\times n$ matrix and $2$ is an eigenvalue of $A$, show that $4$ is an eigenvalue of $2A$.

__Solution:__

Let $\vec{v}$ be an eigenvector of $A$ corresponding to $\lambda = 2$. We have:

$$
(2A)\vec{v} =  2 A\vec{v} = 2 (2\vec{v}) = 4 \vec{v}
$$

3. If $A$ is an invertible matrix with eigenvalue $\lambda$ show that $A^{-1}$ has eigenvalue $1/\lambda.$ 
    
    
__Solution:__

Let $\vec{v}$ be an eigenvector of $A$ corresponding to $\lambda$. We have 

$$
A\vec{v} = \lambda \vec{v} \iff A^{-1} (A\vec{v}) = A^{-1} (\lambda\vec{v}) \iff \vec{v} = \lambda A^{-1} \vec{v} \iff A^{-1} \vec{v} = \frac{1}{\lambda}\vec{v}. 
$$



4.  Let $A = \begin{bmatrix} 1 & 3 & 3\\ -3 & -5 &-3\\ 3 & 3 & 1 \end{bmatrix}$. 

    a. Find the eigenvalues of $A$ and their multiplicities.
    
    b. For each eigenvalue in part (a) find the corresponding eigenspace. 
    
    c. Find the dimension of each eigenspace in part (b) by finding a basis for it. How this result is related to your answer to part (a)?   




__Solution:__

In [1]:
import numpy as np

#(a)

A = np.array([[1,3,3], [-3, -5, -3], [3,3,1]])

#eigenvalues of A
np.linalg.eigvals(A)

array([ 1., -2., -2.])

(b)

$$
E_{1}= Null(\begin{bmatrix}
    1-1 & 3 & 3\\
    -3 & -5-1 &-3\\
    3 & 3 & 1-1
\end{bmatrix})
$$

and 

$$
E_{-2}= Null(\begin{bmatrix}
    1 +2 & 3 & 3\\
    -3 & -5+2 &-3\\
    3 & 3 & 1+2
\end{bmatrix})
$$

(c)
A basis for $E_1: \left\{ \ \begin{bmatrix} 1\\-1\\1 \end{bmatrix}\ \right\}$. The dimension of $E_1$ is then $1$.
    
 
 


A basis for $E_{-2}: \left\{\ \begin{bmatrix} -1\\ 1 \\ 0 \end{bmatrix}, \begin{bmatrix} -1 \\ 0\\ 1 \end{bmatrix}\ \right\}$
    
The dimension of $E_{-2}$ is then $2$.


The multiplicity of $\lambda = 1$ is equal to the dimension of $E_{1}$.
The multiplicity of $\lambda = -2$ is equal to the dimension of $E_{-2}$.

In general the multiplicity of an eigenvalue $\lambda$ is not equal to the dimension of its eigenspace $E_{\lambda}$. However, when it does we say the matrix is diagonalizable. We will learn more about this in the next section.

# 4.2 Diagonalization

1. Suppose
$
M = \begin{bmatrix} 2 & 4 & 3 \\ -4 & -6 & -3 \\ 3 & 3 & 1 \end{bmatrix}.
$

    a. Is M diagonalizable? If yes find a diagonalization for it.
    
    b. Use this diagonalization to compute $M^100$



__Solution:__

(a)

In [13]:
M = np.array([[2,4,3], [-4,-6,3], [3,3,1]])
# find evalues and evectors
evalues, evectors = np.linalg.eig(M)

print("eigenvalues = ",  evalues)

eigenvalues =  [-5. -2.  4.]


Since we have three distinct eigenvalues, $M$ is diagonalizable. 

In [14]:
lambda_1 = evalues[0]
lambda_2 = evalues[1]
lambda_3 = evalues[2]

# finding the diagonal matrix D
D = np.array([[lambda_1, 0, 0], [0, lambda_2, 0], [0, 0, lambda_3]]) 

# finding the invirtible matrix P
P = evectors

# finding the inverse of matrix P

Q = np.linalg.inv(P)

#sanity check: A = PDQ

P @ D @ Q

array([[ 2.,  4.,  3.],
       [-4., -6.,  3.],
       [ 3.,  3.,  1.]])

(b): Note that

$$
A^{100} = P D^{100} Q
$$

In [15]:
# finding D^10

## digonal entries to the power of 10 (rounded it up to the closest intiger)
a1 = np.rint(pow(evalues[0], 100))
a2 = np.rint(pow(evalues[1], 100))
a3 = np.rint(pow(evalues[2], 100))

# computing D to the power of 10
D100 = np.array([[ a1, 0, 0], [0, a2, 0], [0, 0, a3]]) 

print(D100)

A100 = P @ D100 @ Q

A100

[[7.88860905e+69 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.26765060e+30 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.60693804e+60]]


array([[-4.38256058e+69, -4.38256058e+69,  4.38256059e+69],
       [ 9.64163329e+69,  9.64163329e+69, -9.64163329e+69],
       [-2.62953635e+69, -2.62953635e+69,  2.62953635e+69]])

2. Suppose $C=\begin{bmatrix}
3 & 0 & 1 & 0 & 0\\
0 & 3 & 0 & 0 & 0\\
0 & 0 & 3 & 0 & 0\\
0 & 0 & 3 & 2 & 0\\
0 & 0 & 0 & 0 & 2
\end{bmatrix}$. Is $C$ diagonalizable?



__Solution:__


No. The eigenvalues of $C$ are 3 with multiplicity 3 and 2 with multiplicity 2. We show C is not diagonalizable by looking for the dimension of $E_3 = Nul(C-3I).$

In [17]:
C = np.array([[3,0,1, 0, 0], [0,3,0,0,0], [0,0,3,0,0], [0,0,3,2,0], [0,0,0,0,2]])

# find eigenvalues and eigenvectors
evalues, evectors = np.linalg.eig(C)

print('eigenvalues = ',evalues)

#identity matrix
I = np.eye(5)

# constructing C-3I
C - 3*I

eigenvalues =  [3. 3. 2. 3. 2.]


array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3., -1.,  0.],
       [ 0.,  0.,  0.,  0., -1.]])

From this we can see that the number of non-pivot columns in $E_3$ is 2 which is not equal to 3. Thus $C$ is not diagonalizable.

3. Let $A$ be a $5\times 5$ matrix, with two eigenvalues. One eigenspace is three-dimensional, the other is two dimensional. Is $A$ diagonalizable?




__Solution:__

Yes, since we have $5$ linearly independent eigenvectors of $A.$



4. Compute $A^{200}$ where $A = \begin{bmatrix} 4 & -3\\ 2 & -1 \end{bmatrix}$. 


__Solution:__

We can easily check that $A$ has two distinct eigenvalues and therefore diagonalizable. Let's find a diagonalization for it.

In [20]:
A = np.array([[1,2], [4,3]])

# find evalues and evectors
evalues, evectors = np.linalg.eig(A)

lambda_1 = evalues[0]
lambda_2 = evalues[1]

# finding the diagonal matrix D
D = np.array([[lambda_1, 0], [0, lambda_2]]) 

# finding the invirtible matrix P
P = evectors

# finding the inverse of matrix P

Q = np.linalg.inv(P)

#sanity check: A = PDQ

P @ D @ Q

array([[1., 2.],
       [4., 3.]])

In [22]:
# finding D^200

a1 = np.rint(pow(evalues[0], 200))
a2 = np.rint(pow(evalues[1], 200))

# computing D to the power of 20
D200 = np.array([[ a1, 0], [0, a2]]) 

# computing A to the power of 20

A200 = P @ D200 @ Q

A200

array([[2.07433843e+139, 2.07433843e+139],
       [4.14867685e+139, 4.14867685e+139]])

# 4.3 Discrete Dynamical Systems 

1. Let $A$ be a $2\times 2$ matrix with eigenvalues $5$ and $\frac{1}{5}$ and corresponding eigenvectors $\begin{bmatrix} 1 \\ 1 \end{bmatrix}$ and $\begin{bmatrix} -1 \\ 1 \end{bmatrix}$. Let $\vec{x}_k$ be a solution of $\vec{x}_{k+1} = A \vec{x}_{k}$, $\vec{x}_0 = \begin{bmatrix} 9 \\ 1 \end{bmatrix}$ .

a. Compute $\vec{x}_1 = A\vec{x}_0$

b. Find a formula for $\vec{x}_k$ involving $k$ and the eigenvectors of $A$.

c. Describe what happens when $k\to \infty$. 


__Solution:__



In [23]:
#(a)

# intial vector
x_0 = np.array([9,1])

# matrix A
A = np.array([[1,-1],[1,1]])

#x_1
x_1 = A @ x_0
x_1

array([ 8, 10])

(b)

Assume 

$$
\vec{x_0} = d_1 \vec{v_1} + d_2 \vec{v_2} \quad \text{for some } d_1, d_2 \quad (*)
$$

Then 

$$
\vec{x_k} = d_1 (\lambda_1)^{k} \vec{v_1} + d_2 (\lambda_2)^{k}\vec{v_2}
$$

In [24]:
# a matrix whose columns are eigenvectors
P = np.array([[1,-1], [1,1]])

#solving (*) for coeeficients d1 and d2

D = np.linalg.solve(P, x_0)

print('d1 = ', D[0], ' and d2 = ',D[1] )

d1 =  5.0  and d2 =  -4.0


Therefore, we have 

$$
\vec{x_k} = 5 (5)^{k} \begin{bmatrix} 1 \\ 1 \end{bmatrix} -4 (\frac{1}{5})^{k}\vec{v_2} \begin{bmatrix} -1 \\ 1 \end{bmatrix}
$$


(C) 

$$
x_{k+1} \approx 5 (5)^{k+1}\begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$