# 5.4 Least-Squares Problems

Linear systems arising in applications are often inconsistent. In such situations, the best one can do is to find a vector $\vec{x}'$ that makes $A\vec{x}$ as close as possible to $\vec{b}$. We think of $A\vec{x}$ as an approximation of $\vec{b}$. The smaller $\|\vec{b} - A\vec{x}\|$, the better the approximation. Therefore, we are looking for a vector $\hat{y}$ such that $\|\vec{b} - A\hat{x}\|$ is as small as possible. Such $\vec{y}$ is called the _least square solution_ of $A\vec{x} = \vec{b}$. The name is motivated by the fact that $\|\vec{b} - A\hat{x}\|$ is the square root of a sum of squares. In this section we explore this idea further.

Let $A\vec{x} = \vec{b}$ be inconsistent, which implies $\vec{b}\notin \text{col}(A)$. Note that no matter what $\vec{x}$ is, $A\vec{x}$ lies in $\text{col}(A)$. From Section 5.2, we know that the closest point to $\vec{b}$ in $\text{col}(A)$ is the projection of $\vec{b}$ onto $\text{col}(A)$ (the best approximation problem). Let $\hat{b} = \text{proj}_{\text{col}(A)}(\vec{b})$. Since $A\vec{x} = \hat{b}$ is consistent, there are $\hat{x}$ such that $A\hat{x} = \hat{b}$. $\hat{x}$ is a least square solution of $A\vec{x} = \vec{b}$. Recall that $\vec{b} -\hat{b}$ is orthogonal to $\text{col}(A)$, and thus so is $\vec{b} - A\hat{x}$. In other words, $\vec{b} - A\hat{x}$ is orthogonal to each column of $A$, and we have:

$$
A^{T}(\vec{b} - A\hat{x}) = 0 \quad \text{or} \quad A^{T}A\vec{x}= A^{T}\vec{b}.
$$

The equation $A^{T}A\vec{x}= A^{T}\vec{b}$ is called the __normal equation__ for $A\vec{x} = \vec{b}$.

__Theorem 1__

The set of least-squares solutions of $A\vec{x} = \vec{b}$ coincides with the nonempty set of solutions of the normal equation $A^{T}A\vec{x}= A^{T}\vec{b}$.




__Example 1__

Find a least-squares solution of the inconsistent system $A\vec{x} = \vec{b}$ for $A = \begin{bmatrix} 4 & 2\\ 0 & 2 \\ 1 & 1 \end{bmatrix}$ and $\vec{b} = \begin{bmatrix} 2 \\0 \\11 \end{bmatrix}$.

__Solution:__ First, let's find $A^TA$ and $A^T\vec{b}$:

In [1]:
import numpy as np

A = np.array([[4,0], [0,2], [1,1]])

b = np.array([[2], [0], [11]])

# compute A^TA
ATA = A.transpose() @ A 

print("A^TA = \n", ATA)

# compute A^Tb
ATb = A.transpose() @ b 

print("\n A^Tb = \n", ATb)

A^TA = 
 [[17  1]
 [ 1  5]]

 A^Tb = 
 [[19]
 [11]]


Thus, the normal equation for $A\vec{x} = \vec{b}$ is given by:

$$
\begin{bmatrix} 17 & 1 \\ 1 & 5 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 19 \\ 11 \end{bmatrix}.
$$

To solve this equation, we can use row operations; alternatively, since $A^TA$ is invertible and $2 \times 2$, we can use the invertible matrix theorem. In many calculations, $A^TA$ is invertible, but this is not always the case. In Theorem 2, we will see when this is true. The least square solution $\hat{x}$ is given by:

$$
\hat{x} = (A^TA)^{-1} A^{T}\vec{b}.
$$

In [2]:
# computing x_hat

x_hat = np.linalg.inv(ATA) @ ATb
x_hat

array([[1.],
       [2.]])


__Example 2__ Find a least-squares solution of the inconsistent system $A\vec{x} = \vec{b}$ for $A = \begin{bmatrix} 1 & 1 & 0 & 0\\ 1 & 1 & 0 & 0\\ 1 & 0 & 1 & 0\\1 & 0 & 1 & 0 \\1 & 0 & 0 & 1\\1 & 0 & 0 & 1 \end{bmatrix}$ and $\vec{b} = \begin{bmatrix} -3 \\-1 \\0 \\2 \\5 \\1 \end{bmatrix}$. 

__Solution__ 

Let's set up the normal equation for $A\vec{x} = \vec{b}$, and find a solution for it. 

In [3]:
A = np.array([[1,1,0,0], [1,1,0,0], [1,0,1,0],[1,0,1,0], [1,0,0,1],[1,0,0,1]])

b = np.array([[-3,-1,0,2,5,1]])


# compute A^TA
ATA = A.T @ A
print('A^TA = \n', ATA)

# compute A^Tb
ATb = A.T @ b.T
print('\n A^Tb = \n', ATb)

A^TA = 
 [[6 2 2 2]
 [2 2 0 0]
 [2 0 2 0]
 [2 0 0 2]]

 A^Tb = 
 [[ 4]
 [-4]
 [ 2]
 [ 6]]


Thus, the normal equation is 

$$
\begin{bmatrix} 6 & 2 & 2 & 2 \\ 2 & 2 & 0 & 0 \\ 2 & 0 & 2 & 0 \\ 2 & 0 & 0 & 2 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{bmatrix} = \begin{bmatrix} 4 \\ -4 \\ 2 \\6 \end{bmatrix}
$$

To solve this equation we form its augmented matrix:

In [4]:
#aumented 
M = np.concatenate((ATA, ATb), axis=1)
M

array([[ 6,  2,  2,  2,  4],
       [ 2,  2,  0,  0, -4],
       [ 2,  0,  2,  0,  2],
       [ 2,  0,  0,  2,  6]])

Call row operations:

In [5]:
# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row1 by the sum of itself and a multiple of rpw2 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [6]:
M1 = swap(M, 0, 2)
M1

array([[ 2.,  0.,  2.,  0.,  2.],
       [ 2.,  2.,  0.,  0., -4.],
       [ 6.,  2.,  2.,  2.,  4.],
       [ 2.,  0.,  0.,  2.,  6.]])

In [7]:
M2 = scale(M1, 0, 1/2)
M2

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 2.,  2.,  0.,  0., -4.],
       [ 6.,  2.,  2.,  2.,  4.],
       [ 2.,  0.,  0.,  2.,  6.]])

In [8]:
M3 = replace(M2, 1, 0, -2)
M3

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 0.,  2., -2.,  0., -6.],
       [ 6.,  2.,  2.,  2.,  4.],
       [ 2.,  0.,  0.,  2.,  6.]])

In [9]:
M4 = replace(M3, 2, 0, -6)
M4

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 0.,  2., -2.,  0., -6.],
       [ 0.,  2., -4.,  2., -2.],
       [ 2.,  0.,  0.,  2.,  6.]])

In [10]:
M5 = replace(M4, 3, 0, -2)
M5

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 0.,  2., -2.,  0., -6.],
       [ 0.,  2., -4.,  2., -2.],
       [ 0.,  0., -2.,  2.,  4.]])

In [11]:
M6 = scale(M5, 1, 1/2)
M6

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 0.,  1., -1.,  0., -3.],
       [ 0.,  2., -4.,  2., -2.],
       [ 0.,  0., -2.,  2.,  4.]])

In [12]:
M7 = replace(M6, 2, 1, -2)
M7

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 0.,  1., -1.,  0., -3.],
       [ 0.,  0., -2.,  2.,  4.],
       [ 0.,  0., -2.,  2.,  4.]])

In [13]:
M8 = scale(M7, 2, -1/2)
M8

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 0.,  1., -1.,  0., -3.],
       [-0., -0.,  1., -1., -2.],
       [ 0.,  0., -2.,  2.,  4.]])

In [14]:
M9 = replace(M8, 3, 2, 2)
M9

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 0.,  1., -1.,  0., -3.],
       [-0., -0.,  1., -1., -2.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
M10 = replace(M9, 0, 2, -1)
M10

array([[ 1.,  0.,  0.,  1.,  3.],
       [ 0.,  1., -1.,  0., -3.],
       [-0., -0.,  1., -1., -2.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
M11 = replace(M10, 1, 2, 1)
M11

array([[ 1.,  0.,  0.,  1.,  3.],
       [ 0.,  1.,  0., -1., -5.],
       [-0., -0.,  1., -1., -2.],
       [ 0.,  0.,  0.,  0.,  0.]])

The general solution is $x_1 = 3 - x_4$, $x_2 = -5 + x_4$, $x_3 = -2 + x_4$, and $x_4$ is a free parameter. So the general least-squares solution of $A\vec{x} = \vec{b}$ has the form:

$$
\hat{x} = \begin{bmatrix} 3 \\ -5 \\ -2 \\ 0 \end{bmatrix} + x_4 \begin{bmatrix} -1 \\ 1 \\ 1 \\ 0 \end{bmatrix}.
$$

Any linear system $A\vec{x} = \vec{b}$ admits at least one least-squares solution (the orthogonal projection $\hat{b}$). For example, the least-squares solution of $A\vec{x} = \vec{b}$ in Example 1 was unique, while the linear system in Example 2 has infinitely many least-squares solutions.

The next theorem gives useful criteria for determining when there is only one least-squares solution.

__Theorem 2__ 

Let $A$ be an $m\times n$ matrix. The following statements are equivalent:

   1. The equation $A\vec{x} = \vec{b}$ has a unique least-squares solution for each $\vec{b}\in \mathbb{R}^n$.
   
   2. The columns of $A$ are linearly independent.
   
   3. The matrix $A^TA$ is invertible.
   
In any of these cases, the least-squares solution $\hat{x}$ is given by:

$$
\hat{x} = (A^TA)^{-1} A^T \vec{b}.
$$

Moreover, if $A = QR$ is a $QR$-factorization of $A$, then the least-squares solution $\hat{x}$ is given by:

$$
\hat{x} = R^{-1} Q^{T} \vec{b}. \quad (*)
$$

__Example 3:__

Let $A = \begin{bmatrix} 1 & 3 & 5 \\ 1 & 1 & 0 \\ 1 & 1 & 2 \\ 1 & 3 & 3\end{bmatrix}$ and $\vec{b} = \begin{bmatrix} 3 \\ 5 \\ 7 \\ -3 \end{bmatrix}$. Find a least-squares solution of $A\vec{x} = \vec{b}$.

__Solution:__

A QR-factorization of $A$ can be obtained as in Section 5.3 using `numpy.linalg.qr()`:

In [17]:
A = np.array([[1,3,5], [1,1,0], [1,1,2],[1,3,3]])

# QR factorization

Q, R = np.linalg.qr(A)

print('Q = \n', Q, '\n')

print('R = \n', R)

Q = 
 [[-0.5  0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5 -0.5 -0.5]
 [-0.5  0.5  0.5]] 

R = 
 [[-2. -4. -5.]
 [ 0.  2.  3.]
 [ 0.  0. -2.]]


Now we compute  $\hat{x} = R^{-1} Q^{T} \vec{b}:$

In [18]:
# setup
b = np.array([[3, 5, 7, -3]]).T

#computing x_hat

x_hat = np.linalg.inv(R) @ Q.T @ b
x_hat

array([[10.],
       [-6.],
       [ 2.]])

## Numerical Note

Since $R$ in $(*)$ is an upper triangular matrix, we can alternatively compute $\hat{x}$ by finding the exact solutions of:

$$
R\hat{x} = Q^{T} \vec{b}. \quad (**)
$$

For large matrices, solving $(**)$ by back-substitution or row operations is faster than computing $R^{-1}$ and using $(*)$.

## Excercises



1. Let $A = \begin{bmatrix} 1 & -3 & -3 \\  1 & 5 & 1 \\ 1 & 1 & 2 \\ 1 & 7 & 2\end{bmatrix}$ and $\vec{b} = \begin{bmatrix} 5 \\ -3 \\ -5 \end{bmatrix}$.

    a.  Find a least-squares solution of $A\vec{x} = \vec{b}$.
    
    b. Compute the associated least-squares error $\| \vec{b} - A\hat{x}\|$.




2. Describe all least-squares solutions of the system

$$
\begin{align*}
    x + y &= 2 \\ 
    x + y &= 4 \\ 
\end{align*}
$$